# 운영 환경 설정
server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/qiro_prod}
    username: ${DATABASE_USERNAME:qiro}
    password: ${DATABASE_PASSWORD}
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 50
      minimum-idle: 10
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        generate_statistics: false

# Actuator 보안 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
  security:
    enabled: true

# 로깅 설정 (운영 환경)
logging:
  level:
    com.qiro: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.web: WARN
  file:
    name: logs/qiro-application.log

# QIRO 운영 환경 설정
qiro:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: PT30M # 운영에서는 30분
    refresh-token-expiration: P1D   # 운영에서는 1일
  
  database:
    connection-timeout: PT20S
    max-pool-size: 50
    min-pool-size: 10
    idle-timeout: PT5M
    max-lifetime: PT15M
  
  file:
    upload-path: ${FILE_UPLOAD_PATH:/app/uploads}
    max-file-size: 5242880 # 5MB (운영에서는 더 작게)
    pdf-generation-path: ${PDF_GENERATION_PATH:/app/pdf-temp}
  
  notification:
    email:
      enabled: ${EMAIL_ENABLED:true}
      host: ${EMAIL_HOST:smtp.gmail.com}
      port: ${EMAIL_PORT:587}
      username: ${EMAIL_USERNAME}
      password: ${EMAIL_PASSWORD}
      from-address: ${EMAIL_FROM_ADDRESS:noreply@qiro.com}
      from-name: ${EMAIL_FROM_NAME:QIRO 시스템}
    sms:
      enabled: ${SMS_ENABLED:false}
      provider: ${SMS_PROVIDER:none}
      api-key: ${SMS_API_KEY:}
      api-secret: ${SMS_API_SECRET:}
      from-number: ${SMS_FROM_NUMBER:}
    push:
      enabled: ${PUSH_ENABLED:false}
      fcm-server-key: ${FCM_SERVER_KEY:}
      apns-key-id: ${APNS_KEY_ID:}
      apns-team-id: ${APNS_TEAM_ID:}
      apns-key-path: ${APNS_KEY_PATH:}
  
  monitoring:
    metrics:
      enabled: true
      export-interval: PT30S # 운영에서는 더 자주
      retention-period: P90D  # 운영에서는 더 길게
    health:
      disk-space-threshold: ${HEALTH_DISK_THRESHOLD:2147483648} # 2GB
      memory-threshold: ${HEALTH_MEMORY_THRESHOLD:0.85}
      database-timeout: PT3S
    logging:
      level: ${LOG_LEVEL:WARN}
      max-file-size: ${LOG_MAX_FILE_SIZE:50MB}
      max-history: ${LOG_MAX_HISTORY:60}
      total-size-cap: ${LOG_TOTAL_SIZE_CAP:5GB}
  
  business:
    invoice:
      default-due-days: ${INVOICE_DEFAULT_DUE_DAYS:30}
      late-fee-rate: ${INVOICE_LATE_FEE_RATE:0.02}
      late-fee-grace-period: ${INVOICE_LATE_FEE_GRACE_PERIOD:3}
      auto-send-enabled: ${INVOICE_AUTO_SEND_ENABLED:true}
      pdf-generation-enabled: ${INVOICE_PDF_GENERATION_ENABLED:true}
    payment:
      supported-methods: ${PAYMENT_SUPPORTED_METHODS:CASH,BANK_TRANSFER,CARD,VIRTUAL_ACCOUNT}
      refund-grace-period: ${PAYMENT_REFUND_GRACE_PERIOD:P7D}
      auto-confirmation-enabled: ${PAYMENT_AUTO_CONFIRMATION_ENABLED:false}
    maintenance:
      default-priority: ${MAINTENANCE_DEFAULT_PRIORITY:MEDIUM}
      auto-assignment-enabled: ${MAINTENANCE_AUTO_ASSIGNMENT_ENABLED:true}
      escalation-threshold: ${MAINTENANCE_ESCALATION_THRESHOLD:PT24H}
      reminder-interval: ${MAINTENANCE_REMINDER_INTERVAL:PT4H}