# 기본 설정
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: never
    include-message: always

spring:
  application:
    name: qiro-backend
  
  profiles:
    active: local
  
  datasource:
    url: jdbc:postgresql://localhost:5432/qiro_dev
    username: qiro
    password: p@ssword
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 5
      pool-name: QiroHikariCP
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  health:
    diskspace:
      enabled: true
      threshold: 1GB
  metrics:
    export:
      prometheus:
        enabled: true

# 로깅 설정
logging:
  level:
    com.qiro: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

# QIRO 애플리케이션 설정
qiro:
  jwt:
    secret: ${JWT_SECRET:qiro-jwt-secret-key-for-development-only-change-in-production}
    access-token-expiration: PT1H
    refresh-token-expiration: P7D
    issuer: qiro-backend
  
  database:
    connection-timeout: PT30S
    max-pool-size: 20
    min-pool-size: 5
    idle-timeout: PT10M
    max-lifetime: PT30M
  
  file:
    upload-path: ./uploads
    max-file-size: 10485760 # 10MB
    allowed-extensions:
      - jpg
      - jpeg
      - png
      - pdf
      - doc
      - docx
      - xls
      - xlsx
    pdf-generation-path: ./pdf-temp
  
  notification:
    email:
      enabled: true
      host: localhost
      port: 587
      username: ""
      password: ""
      from-address: noreply@qiro.com
      from-name: QIRO 시스템
    sms:
      enabled: false
      provider: none
      api-key: ""
      api-secret: ""
      from-number: ""
    push:
      enabled: false
      fcm-server-key: ""
      apns-key-id: ""
      apns-team-id: ""
      apns-key-path: ""
  
  monitoring:
    metrics:
      enabled: true
      export-interval: PT1M
      retention-period: P30D
    health:
      disk-space-threshold: 1073741824 # 1GB
      memory-threshold: 0.9
      database-timeout: PT5S
    logging:
      level: INFO
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB
  
  business:
    invoice:
      default-due-days: 30
      late-fee-rate: 0.02
      late-fee-grace-period: 3
      auto-send-enabled: true
      pdf-generation-enabled: true
    payment:
      supported-methods:
        - CASH
        - BANK_TRANSFER
        - CARD
        - VIRTUAL_ACCOUNT
      refund-grace-period: P7D
      auto-confirmation-enabled: false
    maintenance:
      default-priority: MEDIUM
      auto-assignment-enabled: true
      escalation-threshold: PT24H
      reminder-interval: PT4H