-- =====================================================
-- 포괄적인 컬럼 한글 커멘트 추가 스크립트
-- 커멘트가 없는 주요 테이블들의 모든 컬럼에 한글 커멘트 추가
-- =====================================================

-- 예방 유지보수 실행 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.preventive_maintenance_executions.execution_id IS '실행 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.plan_id IS '유지보수 계획 식별자 (UUID)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.asset_id IS '시설 자산 식별자 (UUID)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.execution_number IS '실행 번호';
COMMENT ON COLUMN bms.preventive_maintenance_executions.execution_type IS '실행 유형';
COMMENT ON COLUMN bms.preventive_maintenance_executions.execution_date IS '실행 일자';
COMMENT ON COLUMN bms.preventive_maintenance_executions.planned_start_time IS '계획 시작 시간';
COMMENT ON COLUMN bms.preventive_maintenance_executions.actual_start_time IS '실제 시작 시간';
COMMENT ON COLUMN bms.preventive_maintenance_executions.planned_end_time IS '계획 종료 시간';
COMMENT ON COLUMN bms.preventive_maintenance_executions.actual_end_time IS '실제 종료 시간';
COMMENT ON COLUMN bms.preventive_maintenance_executions.execution_status IS '실행 상태';
COMMENT ON COLUMN bms.preventive_maintenance_executions.assigned_technician IS '담당 기술자';
COMMENT ON COLUMN bms.preventive_maintenance_executions.work_description IS '작업 설명';
COMMENT ON COLUMN bms.preventive_maintenance_executions.completion_notes IS '완료 메모';
COMMENT ON COLUMN bms.preventive_maintenance_executions.quality_rating IS '품질 평가';
COMMENT ON COLUMN bms.preventive_maintenance_executions.total_cost IS '총 비용';
COMMENT ON COLUMN bms.preventive_maintenance_executions.labor_hours IS '작업 시간';
COMMENT ON COLUMN bms.preventive_maintenance_executions.materials_used IS '사용 자재 (JSON)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.tools_used IS '사용 도구 (JSON)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.safety_measures IS '안전 조치';
COMMENT ON COLUMN bms.preventive_maintenance_executions.environmental_conditions IS '환경 조건';
COMMENT ON COLUMN bms.preventive_maintenance_executions.before_photos IS '작업 전 사진';
COMMENT ON COLUMN bms.preventive_maintenance_executions.after_photos IS '작업 후 사진';
COMMENT ON COLUMN bms.preventive_maintenance_executions.inspection_results IS '점검 결과 (JSON)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.recommendations IS '권고사항';
COMMENT ON COLUMN bms.preventive_maintenance_executions.next_maintenance_date IS '다음 유지보수 예정일';
COMMENT ON COLUMN bms.preventive_maintenance_executions.warranty_period IS '보증 기간 (일)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.created_at IS '생성 일시';
COMMENT ON COLUMN bms.preventive_maintenance_executions.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.preventive_maintenance_executions.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.preventive_maintenance_executions.updated_by IS '수정자 사용자 ID';

-- 안전 사고 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.safety_incidents.incident_id IS '사고 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.safety_incidents.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.safety_incidents.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.safety_incidents.incident_number IS '사고 번호';
COMMENT ON COLUMN bms.safety_incidents.incident_type IS '사고 유형';
COMMENT ON COLUMN bms.safety_incidents.severity_level IS '심각도 수준';
COMMENT ON COLUMN bms.safety_incidents.incident_date IS '사고 발생일';
COMMENT ON COLUMN bms.safety_incidents.incident_time IS '사고 발생 시간';
COMMENT ON COLUMN bms.safety_incidents.location IS '사고 발생 위치';
COMMENT ON COLUMN bms.safety_incidents.description IS '사고 설명';
COMMENT ON COLUMN bms.safety_incidents.injured_persons IS '부상자 수';
COMMENT ON COLUMN bms.safety_incidents.fatalities IS '사망자 수';
COMMENT ON COLUMN bms.safety_incidents.property_damage IS '재산 피해액';
COMMENT ON COLUMN bms.safety_incidents.immediate_cause IS '직접 원인';
COMMENT ON COLUMN bms.safety_incidents.root_cause IS '근본 원인';
COMMENT ON COLUMN bms.safety_incidents.contributing_factors IS '기여 요인';
COMMENT ON COLUMN bms.safety_incidents.weather_conditions IS '기상 조건';
COMMENT ON COLUMN bms.safety_incidents.witnesses IS '목격자 정보 (JSON)';
COMMENT ON COLUMN bms.safety_incidents.emergency_response IS '응급 대응 내역';
COMMENT ON COLUMN bms.safety_incidents.medical_treatment IS '의료 처치 내역';
COMMENT ON COLUMN bms.safety_incidents.investigation_status IS '조사 상태';
COMMENT ON COLUMN bms.safety_incidents.investigator_id IS '조사자 사용자 ID';
COMMENT ON COLUMN bms.safety_incidents.investigation_findings IS '조사 결과';
COMMENT ON COLUMN bms.safety_incidents.corrective_actions IS '시정 조치';
COMMENT ON COLUMN bms.safety_incidents.preventive_measures IS '예방 조치';
COMMENT ON COLUMN bms.safety_incidents.regulatory_notification IS '규제 기관 신고 여부';
COMMENT ON COLUMN bms.safety_incidents.insurance_claim IS '보험 청구 여부';
COMMENT ON COLUMN bms.safety_incidents.lessons_learned IS '교훈 사항';
COMMENT ON COLUMN bms.safety_incidents.photos IS '사고 현장 사진';
COMMENT ON COLUMN bms.safety_incidents.documents IS '관련 문서';
COMMENT ON COLUMN bms.safety_incidents.created_at IS '생성 일시';
COMMENT ON COLUMN bms.safety_incidents.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.safety_incidents.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.safety_incidents.updated_by IS '수정자 사용자 ID';

-- 임차인 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.tenants.tenant_id IS '임차인 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.tenants.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.tenants.unit_id IS '세대 식별자 (UUID)';
COMMENT ON COLUMN bms.tenants.tenant_type IS '임차인 유형 (INDIVIDUAL, CORPORATE)';
COMMENT ON COLUMN bms.tenants.name IS '임차인명';
COMMENT ON COLUMN bms.tenants.id_number IS '주민등록번호/사업자등록번호';
COMMENT ON COLUMN bms.tenants.phone_number IS '전화번호';
COMMENT ON COLUMN bms.tenants.mobile_number IS '휴대폰 번호';
COMMENT ON COLUMN bms.tenants.email IS '이메일';
COMMENT ON COLUMN bms.tenants.address IS '주소';
COMMENT ON COLUMN bms.tenants.emergency_contact_name IS '비상 연락처 이름';
COMMENT ON COLUMN bms.tenants.emergency_contact_phone IS '비상 연락처 전화번호';
COMMENT ON COLUMN bms.tenants.emergency_contact_relationship IS '비상 연락처 관계';
COMMENT ON COLUMN bms.tenants.occupation IS '직업';
COMMENT ON COLUMN bms.tenants.workplace IS '직장';
COMMENT ON COLUMN bms.tenants.monthly_income IS '월 소득';
COMMENT ON COLUMN bms.tenants.family_members IS '가족 구성원 수';
COMMENT ON COLUMN bms.tenants.pets IS '반려동물 정보';
COMMENT ON COLUMN bms.tenants.vehicle_info IS '차량 정보 (JSON)';
COMMENT ON COLUMN bms.tenants.special_needs IS '특별 요구사항';
COMMENT ON COLUMN bms.tenants.lease_start_date IS '임대 시작일';
COMMENT ON COLUMN bms.tenants.lease_end_date IS '임대 종료일';
COMMENT ON COLUMN bms.tenants.deposit_amount IS '보증금';
COMMENT ON COLUMN bms.tenants.monthly_rent IS '월 임대료';
COMMENT ON COLUMN bms.tenants.payment_method IS '납부 방법';
COMMENT ON COLUMN bms.tenants.bank_account IS '계좌 정보';
COMMENT ON COLUMN bms.tenants.credit_score IS '신용 점수';
COMMENT ON COLUMN bms.tenants.references IS '추천인 정보 (JSON)';
COMMENT ON COLUMN bms.tenants.move_in_date IS '입주일';
COMMENT ON COLUMN bms.tenants.move_out_date IS '퇴거일';
COMMENT ON COLUMN bms.tenants.tenant_status IS '임차인 상태';
COMMENT ON COLUMN bms.tenants.notes IS '비고';
COMMENT ON COLUMN bms.tenants.created_at IS '생성 일시';
COMMENT ON COLUMN bms.tenants.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.tenants.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.tenants.updated_by IS '수정자 사용자 ID';

-- 공급업체 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.suppliers.supplier_id IS '공급업체 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.suppliers.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.suppliers.supplier_name IS '공급업체명';
COMMENT ON COLUMN bms.suppliers.business_registration_number IS '사업자등록번호';
COMMENT ON COLUMN bms.suppliers.tax_registration_number IS '세무등록번호';
COMMENT ON COLUMN bms.suppliers.representative_name IS '대표자명';
COMMENT ON COLUMN bms.suppliers.business_type IS '업종';
COMMENT ON COLUMN bms.suppliers.business_category IS '업태';
COMMENT ON COLUMN bms.suppliers.establishment_date IS '설립일';
COMMENT ON COLUMN bms.suppliers.address IS '주소';
COMMENT ON COLUMN bms.suppliers.postal_code IS '우편번호';
COMMENT ON COLUMN bms.suppliers.phone_number IS '전화번호';
COMMENT ON COLUMN bms.suppliers.fax_number IS '팩스 번호';
COMMENT ON COLUMN bms.suppliers.email IS '이메일';
COMMENT ON COLUMN bms.suppliers.website IS '웹사이트';
COMMENT ON COLUMN bms.suppliers.contact_person IS '담당자명';
COMMENT ON COLUMN bms.suppliers.contact_phone IS '담당자 전화번호';
COMMENT ON COLUMN bms.suppliers.contact_email IS '담당자 이메일';
COMMENT ON COLUMN bms.suppliers.bank_name IS '거래 은행';
COMMENT ON COLUMN bms.suppliers.bank_account IS '계좌 번호';
COMMENT ON COLUMN bms.suppliers.account_holder IS '예금주';
COMMENT ON COLUMN bms.suppliers.credit_rating IS '신용 등급';
COMMENT ON COLUMN bms.suppliers.annual_revenue IS '연간 매출액';
COMMENT ON COLUMN bms.suppliers.employee_count IS '직원 수';
COMMENT ON COLUMN bms.suppliers.certification_info IS '인증 정보 (JSON)';
COMMENT ON COLUMN bms.suppliers.insurance_info IS '보험 정보 (JSON)';
COMMENT ON COLUMN bms.suppliers.quality_rating IS '품질 평가';
COMMENT ON COLUMN bms.suppliers.delivery_rating IS '배송 평가';
COMMENT ON COLUMN bms.suppliers.service_rating IS '서비스 평가';
COMMENT ON COLUMN bms.suppliers.overall_rating IS '종합 평가';
COMMENT ON COLUMN bms.suppliers.contract_start_date IS '계약 시작일';
COMMENT ON COLUMN bms.suppliers.contract_end_date IS '계약 종료일';
COMMENT ON COLUMN bms.suppliers.payment_terms IS '결제 조건';
COMMENT ON COLUMN bms.suppliers.delivery_terms IS '배송 조건';
COMMENT ON COLUMN bms.suppliers.warranty_terms IS '보증 조건';
COMMENT ON COLUMN bms.suppliers.supplier_status IS '공급업체 상태';
COMMENT ON COLUMN bms.suppliers.notes IS '비고';
COMMENT ON COLUMN bms.suppliers.created_at IS '생성 일시';
COMMENT ON COLUMN bms.suppliers.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.suppliers.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.suppliers.updated_by IS '수정자 사용자 ID';

-- 작업 완료 보고서 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.work_completion_reports.report_id IS '보고서 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.work_completion_reports.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.work_completion_reports.work_order_id IS '작업 지시 식별자 (UUID)';
COMMENT ON COLUMN bms.work_completion_reports.report_number IS '보고서 번호';
COMMENT ON COLUMN bms.work_completion_reports.completion_date IS '완료일';
COMMENT ON COLUMN bms.work_completion_reports.technician_id IS '기술자 사용자 ID';
COMMENT ON COLUMN bms.work_completion_reports.work_summary IS '작업 요약';
COMMENT ON COLUMN bms.work_completion_reports.work_details IS '작업 상세 내용';
COMMENT ON COLUMN bms.work_completion_reports.materials_used IS '사용 자재 목록 (JSON)';
COMMENT ON COLUMN bms.work_completion_reports.tools_used IS '사용 도구 목록 (JSON)';
COMMENT ON COLUMN bms.work_completion_reports.labor_hours IS '작업 시간';
COMMENT ON COLUMN bms.work_completion_reports.total_cost IS '총 비용';
COMMENT ON COLUMN bms.work_completion_reports.quality_check_passed IS '품질 검사 통과 여부';
COMMENT ON COLUMN bms.work_completion_reports.safety_compliance IS '안전 규정 준수 여부';
COMMENT ON COLUMN bms.work_completion_reports.customer_satisfaction IS '고객 만족도';
COMMENT ON COLUMN bms.work_completion_reports.before_photos IS '작업 전 사진';
COMMENT ON COLUMN bms.work_completion_reports.after_photos IS '작업 후 사진';
COMMENT ON COLUMN bms.work_completion_reports.test_results IS '테스트 결과 (JSON)';
COMMENT ON COLUMN bms.work_completion_reports.warranty_period IS '보증 기간 (일)';
COMMENT ON COLUMN bms.work_completion_reports.warranty_terms IS '보증 조건';
COMMENT ON COLUMN bms.work_completion_reports.follow_up_required IS '후속 조치 필요 여부';
COMMENT ON COLUMN bms.work_completion_reports.follow_up_date IS '후속 조치 예정일';
COMMENT ON COLUMN bms.work_completion_reports.recommendations IS '권고사항';
COMMENT ON COLUMN bms.work_completion_reports.lessons_learned IS '교훈 사항';
COMMENT ON COLUMN bms.work_completion_reports.approved_by IS '승인자 사용자 ID';
COMMENT ON COLUMN bms.work_completion_reports.approved_at IS '승인 일시';
COMMENT ON COLUMN bms.work_completion_reports.created_at IS '생성 일시';
COMMENT ON COLUMN bms.work_completion_reports.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.work_completion_reports.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.work_completion_reports.updated_by IS '수정자 사용자 ID';-- 공용 시설 테이
블 컬럼 커멘트
COMMENT ON COLUMN bms.common_facilities.facility_id IS '시설 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.common_facilities.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.common_facilities.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.common_facilities.facility_name IS '시설명';
COMMENT ON COLUMN bms.common_facilities.facility_type IS '시설 유형';
COMMENT ON COLUMN bms.common_facilities.location IS '위치';
COMMENT ON COLUMN bms.common_facilities.floor_number IS '층수';
COMMENT ON COLUMN bms.common_facilities.area_size IS '면적 (㎡)';
COMMENT ON COLUMN bms.common_facilities.capacity IS '수용 인원';
COMMENT ON COLUMN bms.common_facilities.operating_hours IS '운영 시간';
COMMENT ON COLUMN bms.common_facilities.booking_required IS '예약 필요 여부';
COMMENT ON COLUMN bms.common_facilities.booking_advance_hours IS '사전 예약 시간';
COMMENT ON COLUMN bms.common_facilities.usage_fee IS '사용료';
COMMENT ON COLUMN bms.common_facilities.maintenance_schedule IS '유지보수 일정';
COMMENT ON COLUMN bms.common_facilities.safety_equipment IS '안전 장비 목록 (JSON)';
COMMENT ON COLUMN bms.common_facilities.access_control IS '출입 통제 방식';
COMMENT ON COLUMN bms.common_facilities.facility_status IS '시설 상태';
COMMENT ON COLUMN bms.common_facilities.last_inspection_date IS '마지막 점검일';
COMMENT ON COLUMN bms.common_facilities.next_inspection_date IS '다음 점검 예정일';
COMMENT ON COLUMN bms.common_facilities.insurance_coverage IS '보험 적용 여부';
COMMENT ON COLUMN bms.common_facilities.emergency_procedures IS '비상 절차';
COMMENT ON COLUMN bms.common_facilities.usage_rules IS '사용 규칙';
COMMENT ON COLUMN bms.common_facilities.contact_person IS '담당자';
COMMENT ON COLUMN bms.common_facilities.contact_phone IS '담당자 연락처';
COMMENT ON COLUMN bms.common_facilities.amenities IS '편의 시설 (JSON)';
COMMENT ON COLUMN bms.common_facilities.accessibility_features IS '접근성 기능';
COMMENT ON COLUMN bms.common_facilities.environmental_controls IS '환경 제어 시설';
COMMENT ON COLUMN bms.common_facilities.cleaning_schedule IS '청소 일정';
COMMENT ON COLUMN bms.common_facilities.usage_statistics IS '사용 통계 (JSON)';
COMMENT ON COLUMN bms.common_facilities.maintenance_cost IS '유지보수 비용';
COMMENT ON COLUMN bms.common_facilities.energy_consumption IS '에너지 소비량';
COMMENT ON COLUMN bms.common_facilities.notes IS '비고';
COMMENT ON COLUMN bms.common_facilities.created_at IS '생성 일시';
COMMENT ON COLUMN bms.common_facilities.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.common_facilities.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.common_facilities.updated_by IS '수정자 사용자 ID';

-- 안전 점검 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.safety_inspections.inspection_id IS '점검 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.safety_inspections.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.safety_inspections.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.safety_inspections.schedule_id IS '점검 일정 식별자 (UUID)';
COMMENT ON COLUMN bms.safety_inspections.inspection_number IS '점검 번호';
COMMENT ON COLUMN bms.safety_inspections.inspection_type IS '점검 유형';
COMMENT ON COLUMN bms.safety_inspections.inspection_date IS '점검 일자';
COMMENT ON COLUMN bms.safety_inspections.inspector_id IS '점검자 사용자 ID';
COMMENT ON COLUMN bms.safety_inspections.inspection_scope IS '점검 범위';
COMMENT ON COLUMN bms.safety_inspections.checklist_items IS '점검 항목 (JSON)';
COMMENT ON COLUMN bms.safety_inspections.overall_status IS '전체 점검 상태';
COMMENT ON COLUMN bms.safety_inspections.pass_rate IS '합격률 (%)';
COMMENT ON COLUMN bms.safety_inspections.critical_findings IS '중요 발견사항';
COMMENT ON COLUMN bms.safety_inspections.minor_findings IS '경미한 발견사항';
COMMENT ON COLUMN bms.safety_inspections.recommendations IS '권고사항';
COMMENT ON COLUMN bms.safety_inspections.corrective_actions IS '시정 조치';
COMMENT ON COLUMN bms.safety_inspections.follow_up_required IS '후속 조치 필요 여부';
COMMENT ON COLUMN bms.safety_inspections.follow_up_date IS '후속 조치 예정일';
COMMENT ON COLUMN bms.safety_inspections.next_inspection_date IS '다음 점검 예정일';
COMMENT ON COLUMN bms.safety_inspections.inspection_photos IS '점검 사진';
COMMENT ON COLUMN bms.safety_inspections.inspection_documents IS '점검 문서';
COMMENT ON COLUMN bms.safety_inspections.weather_conditions IS '기상 조건';
COMMENT ON COLUMN bms.safety_inspections.environmental_factors IS '환경 요인';
COMMENT ON COLUMN bms.safety_inspections.equipment_used IS '사용 장비';
COMMENT ON COLUMN bms.safety_inspections.inspection_duration IS '점검 소요 시간 (분)';
COMMENT ON COLUMN bms.safety_inspections.cost IS '점검 비용';
COMMENT ON COLUMN bms.safety_inspections.regulatory_compliance IS '규제 준수 여부';
COMMENT ON COLUMN bms.safety_inspections.certification_issued IS '인증서 발급 여부';
COMMENT ON COLUMN bms.safety_inspections.certificate_number IS '인증서 번호';
COMMENT ON COLUMN bms.safety_inspections.certificate_expiry IS '인증서 만료일';
COMMENT ON COLUMN bms.safety_inspections.approved_by IS '승인자 사용자 ID';
COMMENT ON COLUMN bms.safety_inspections.approved_at IS '승인 일시';
COMMENT ON COLUMN bms.safety_inspections.created_at IS '생성 일시';
COMMENT ON COLUMN bms.safety_inspections.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.safety_inspections.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.safety_inspections.updated_by IS '수정자 사용자 ID';

-- 예방 조치 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.prevention_measures.measure_id IS '조치 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.prevention_measures.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.prevention_measures.incident_id IS '사고 식별자 (UUID, 선택사항)';
COMMENT ON COLUMN bms.prevention_measures.fault_id IS '고장 식별자 (UUID, 선택사항)';
COMMENT ON COLUMN bms.prevention_measures.measure_type IS '조치 유형';
COMMENT ON COLUMN bms.prevention_measures.priority_level IS '우선순위';
COMMENT ON COLUMN bms.prevention_measures.title IS '조치 제목';
COMMENT ON COLUMN bms.prevention_measures.description IS '조치 설명';
COMMENT ON COLUMN bms.prevention_measures.root_cause_analysis IS '근본 원인 분석';
COMMENT ON COLUMN bms.prevention_measures.proposed_solution IS '제안 해결책';
COMMENT ON COLUMN bms.prevention_measures.implementation_plan IS '실행 계획';
COMMENT ON COLUMN bms.prevention_measures.required_resources IS '필요 자원';
COMMENT ON COLUMN bms.prevention_measures.estimated_cost IS '예상 비용';
COMMENT ON COLUMN bms.prevention_measures.target_completion_date IS '목표 완료일';
COMMENT ON COLUMN bms.prevention_measures.assigned_to IS '담당자 사용자 ID';
COMMENT ON COLUMN bms.prevention_measures.implementation_status IS '실행 상태';
COMMENT ON COLUMN bms.prevention_measures.actual_completion_date IS '실제 완료일';
COMMENT ON COLUMN bms.prevention_measures.actual_cost IS '실제 비용';
COMMENT ON COLUMN bms.prevention_measures.effectiveness_rating IS '효과성 평가';
COMMENT ON COLUMN bms.prevention_measures.monitoring_plan IS '모니터링 계획';
COMMENT ON COLUMN bms.prevention_measures.success_metrics IS '성공 지표';
COMMENT ON COLUMN bms.prevention_measures.lessons_learned IS '교훈 사항';
COMMENT ON COLUMN bms.prevention_measures.stakeholders IS '이해관계자 (JSON)';
COMMENT ON COLUMN bms.prevention_measures.communication_plan IS '소통 계획';
COMMENT ON COLUMN bms.prevention_measures.training_required IS '교육 필요 여부';
COMMENT ON COLUMN bms.prevention_measures.training_plan IS '교육 계획';
COMMENT ON COLUMN bms.prevention_measures.policy_changes IS '정책 변경 사항';
COMMENT ON COLUMN bms.prevention_measures.procedure_updates IS '절차 업데이트';
COMMENT ON COLUMN bms.prevention_measures.documentation IS '관련 문서';
COMMENT ON COLUMN bms.prevention_measures.review_date IS '검토 예정일';
COMMENT ON COLUMN bms.prevention_measures.reviewed_by IS '검토자 사용자 ID';
COMMENT ON COLUMN bms.prevention_measures.review_comments IS '검토 의견';
COMMENT ON COLUMN bms.prevention_measures.created_at IS '생성 일시';
COMMENT ON COLUMN bms.prevention_measures.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.prevention_measures.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.prevention_measures.updated_by IS '수정자 사용자 ID';

-- 외부 청구서 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.external_bills.bill_id IS '청구서 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.external_bills.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.external_bills.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.external_bills.supplier_id IS '공급업체 식별자 (UUID)';
COMMENT ON COLUMN bms.external_bills.bill_number IS '청구서 번호';
COMMENT ON COLUMN bms.external_bills.bill_type IS '청구서 유형';
COMMENT ON COLUMN bms.external_bills.service_period_start IS '서비스 기간 시작일';
COMMENT ON COLUMN bms.external_bills.service_period_end IS '서비스 기간 종료일';
COMMENT ON COLUMN bms.external_bills.issue_date IS '발행일';
COMMENT ON COLUMN bms.external_bills.due_date IS '납부 기한';
COMMENT ON COLUMN bms.external_bills.total_amount IS '총 금액';
COMMENT ON COLUMN bms.external_bills.tax_amount IS '세금';
COMMENT ON COLUMN bms.external_bills.net_amount IS '순 금액';
COMMENT ON COLUMN bms.external_bills.currency IS '통화';
COMMENT ON COLUMN bms.external_bills.payment_terms IS '결제 조건';
COMMENT ON COLUMN bms.external_bills.payment_method IS '결제 방법';
COMMENT ON COLUMN bms.external_bills.payment_status IS '결제 상태';
COMMENT ON COLUMN bms.external_bills.paid_date IS '결제일';
COMMENT ON COLUMN bms.external_bills.paid_amount IS '결제 금액';
COMMENT ON COLUMN bms.external_bills.line_items IS '청구 항목 (JSON)';
COMMENT ON COLUMN bms.external_bills.usage_data IS '사용량 데이터 (JSON)';
COMMENT ON COLUMN bms.external_bills.meter_readings IS '검침 데이터 (JSON)';
COMMENT ON COLUMN bms.external_bills.allocation_method IS '배분 방법';
COMMENT ON COLUMN bms.external_bills.allocation_basis IS '배분 기준';
COMMENT ON COLUMN bms.external_bills.allocated_amounts IS '배분 금액 (JSON)';
COMMENT ON COLUMN bms.external_bills.approval_status IS '승인 상태';
COMMENT ON COLUMN bms.external_bills.approved_by IS '승인자 사용자 ID';
COMMENT ON COLUMN bms.external_bills.approved_at IS '승인 일시';
COMMENT ON COLUMN bms.external_bills.processing_status IS '처리 상태';
COMMENT ON COLUMN bms.external_bills.error_messages IS '오류 메시지';
COMMENT ON COLUMN bms.external_bills.import_batch_id IS '가져오기 배치 ID';
COMMENT ON COLUMN bms.external_bills.original_file_name IS '원본 파일명';
COMMENT ON COLUMN bms.external_bills.file_path IS '파일 경로';
COMMENT ON COLUMN bms.external_bills.notes IS '비고';
COMMENT ON COLUMN bms.external_bills.created_at IS '생성 일시';
COMMENT ON COLUMN bms.external_bills.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.external_bills.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.external_bills.updated_by IS '수정자 사용자 ID';

-- 작업 비용 정산 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.work_cost_settlements.settlement_id IS '정산 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.work_cost_settlements.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.work_cost_settlements.work_order_id IS '작업 지시 식별자 (UUID)';
COMMENT ON COLUMN bms.work_cost_settlements.settlement_number IS '정산 번호';
COMMENT ON COLUMN bms.work_cost_settlements.settlement_date IS '정산일';
COMMENT ON COLUMN bms.work_cost_settlements.settlement_type IS '정산 유형';
COMMENT ON COLUMN bms.work_cost_settlements.labor_cost IS '인건비';
COMMENT ON COLUMN bms.work_cost_settlements.material_cost IS '자재비';
COMMENT ON COLUMN bms.work_cost_settlements.equipment_cost IS '장비비';
COMMENT ON COLUMN bms.work_cost_settlements.overhead_cost IS '간접비';
COMMENT ON COLUMN bms.work_cost_settlements.total_cost IS '총 비용';
COMMENT ON COLUMN bms.work_cost_settlements.budgeted_cost IS '예산 비용';
COMMENT ON COLUMN bms.work_cost_settlements.variance_amount IS '차이 금액';
COMMENT ON COLUMN bms.work_cost_settlements.variance_percentage IS '차이 비율 (%)';
COMMENT ON COLUMN bms.work_cost_settlements.cost_breakdown IS '비용 세부 내역 (JSON)';
COMMENT ON COLUMN bms.work_cost_settlements.labor_hours IS '작업 시간';
COMMENT ON COLUMN bms.work_cost_settlements.hourly_rate IS '시간당 요율';
COMMENT ON COLUMN bms.work_cost_settlements.overtime_hours IS '초과 근무 시간';
COMMENT ON COLUMN bms.work_cost_settlements.overtime_rate IS '초과 근무 요율';
COMMENT ON COLUMN bms.work_cost_settlements.materials_used IS '사용 자재 (JSON)';
COMMENT ON COLUMN bms.work_cost_settlements.equipment_used IS '사용 장비 (JSON)';
COMMENT ON COLUMN bms.work_cost_settlements.subcontractor_costs IS '하청업체 비용 (JSON)';
COMMENT ON COLUMN bms.work_cost_settlements.travel_expenses IS '출장비';
COMMENT ON COLUMN bms.work_cost_settlements.miscellaneous_costs IS '기타 비용';
COMMENT ON COLUMN bms.work_cost_settlements.tax_amount IS '세금';
COMMENT ON COLUMN bms.work_cost_settlements.discount_amount IS '할인 금액';
COMMENT ON COLUMN bms.work_cost_settlements.final_amount IS '최종 금액';
COMMENT ON COLUMN bms.work_cost_settlements.payment_terms IS '결제 조건';
COMMENT ON COLUMN bms.work_cost_settlements.payment_status IS '결제 상태';
COMMENT ON COLUMN bms.work_cost_settlements.invoice_number IS '송장 번호';
COMMENT ON COLUMN bms.work_cost_settlements.invoice_date IS '송장 발행일';
COMMENT ON COLUMN bms.work_cost_settlements.payment_due_date IS '결제 기한';
COMMENT ON COLUMN bms.work_cost_settlements.paid_date IS '결제일';
COMMENT ON COLUMN bms.work_cost_settlements.approved_by IS '승인자 사용자 ID';
COMMENT ON COLUMN bms.work_cost_settlements.approved_at IS '승인 일시';
COMMENT ON COLUMN bms.work_cost_settlements.notes IS '비고';
COMMENT ON COLUMN bms.work_cost_settlements.created_at IS '생성 일시';
COMMENT ON COLUMN bms.work_cost_settlements.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.work_cost_settlements.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.work_cost_settlements.updated_by IS '수정자 사용자 ID';