-- =====================================================
-- 추가 컬럼 한글 커멘트 스크립트
-- 실제 존재하는 컬럼들에만 커멘트 추가
-- =====================================================

-- 임대인 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.lessors.lessor_id IS '임대인 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.lessors.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.lessors.lessor_type IS '임대인 유형 (INDIVIDUAL, CORPORATE)';
COMMENT ON COLUMN bms.lessors.name IS '임대인명';
COMMENT ON COLUMN bms.lessors.business_registration_number IS '사업자등록번호 (법인인 경우)';
COMMENT ON COLUMN bms.lessors.id_number IS '주민등록번호 (개인인 경우)';
COMMENT ON COLUMN bms.lessors.phone_number IS '전화번호';
COMMENT ON COLUMN bms.lessors.mobile_number IS '휴대폰 번호';
COMMENT ON COLUMN bms.lessors.email IS '이메일';
COMMENT ON COLUMN bms.lessors.address IS '주소';
COMMENT ON COLUMN bms.lessors.postal_code IS '우편번호';
COMMENT ON COLUMN bms.lessors.bank_name IS '거래 은행';
COMMENT ON COLUMN bms.lessors.bank_account IS '계좌 번호';
COMMENT ON COLUMN bms.lessors.account_holder IS '예금주';
COMMENT ON COLUMN bms.lessors.tax_id IS '세무 식별 번호';
COMMENT ON COLUMN bms.lessors.representative_name IS '대표자명 (법인인 경우)';
COMMENT ON COLUMN bms.lessors.contact_person IS '담당자명';
COMMENT ON COLUMN bms.lessors.contact_phone IS '담당자 연락처';
COMMENT ON COLUMN bms.lessors.emergency_contact IS '비상 연락처';
COMMENT ON COLUMN bms.lessors.preferred_communication IS '선호 연락 방법';
COMMENT ON COLUMN bms.lessors.property_count IS '보유 부동산 수';
COMMENT ON COLUMN bms.lessors.total_rental_income IS '총 임대 수입';
COMMENT ON COLUMN bms.lessors.tax_withholding_rate IS '원천징수율 (%)';
COMMENT ON COLUMN bms.lessors.payment_schedule IS '임대료 지급 일정';
COMMENT ON COLUMN bms.lessors.contract_preferences IS '계약 선호 조건 (JSON)';
COMMENT ON COLUMN bms.lessors.insurance_info IS '보험 정보 (JSON)';
COMMENT ON COLUMN bms.lessors.legal_representative IS '법정 대리인';
COMMENT ON COLUMN bms.lessors.power_of_attorney IS '위임장 정보';
COMMENT ON COLUMN bms.lessors.lessor_status IS '임대인 상태';
COMMENT ON COLUMN bms.lessors.registration_date IS '등록일';
COMMENT ON COLUMN bms.lessors.last_contact_date IS '마지막 연락일';
COMMENT ON COLUMN bms.lessors.notes IS '비고';
COMMENT ON COLUMN bms.lessors.created_at IS '생성 일시';
COMMENT ON COLUMN bms.lessors.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.lessors.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.lessors.updated_by IS '수정자 사용자 ID';

-- 결제 거래 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.payment_transactions.transaction_id IS '거래 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.payment_transactions.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.payment_transactions.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.payment_transactions.unit_id IS '세대 식별자 (UUID, 선택사항)';
COMMENT ON COLUMN bms.payment_transactions.payer_id IS '납부자 식별자 (UUID)';
COMMENT ON COLUMN bms.payment_transactions.transaction_number IS '거래 번호';
COMMENT ON COLUMN bms.payment_transactions.transaction_type IS '거래 유형 (PAYMENT, REFUND, ADJUSTMENT)';
COMMENT ON COLUMN bms.payment_transactions.payment_method IS '결제 수단';
COMMENT ON COLUMN bms.payment_transactions.transaction_date IS '거래 일시';
COMMENT ON COLUMN bms.payment_transactions.amount IS '거래 금액';
COMMENT ON COLUMN bms.payment_transactions.currency IS '통화';
COMMENT ON COLUMN bms.payment_transactions.exchange_rate IS '환율';
COMMENT ON COLUMN bms.payment_transactions.fee_amount IS '수수료';
COMMENT ON COLUMN bms.payment_transactions.net_amount IS '순 금액';
COMMENT ON COLUMN bms.payment_transactions.reference_number IS '참조 번호';
COMMENT ON COLUMN bms.payment_transactions.bank_name IS '은행명';
COMMENT ON COLUMN bms.payment_transactions.account_number IS '계좌 번호';
COMMENT ON COLUMN bms.payment_transactions.card_number IS '카드 번호 (마스킹)';
COMMENT ON COLUMN bms.payment_transactions.card_type IS '카드 유형';
COMMENT ON COLUMN bms.payment_transactions.approval_number IS '승인 번호';
COMMENT ON COLUMN bms.payment_transactions.merchant_id IS '가맹점 ID';
COMMENT ON COLUMN bms.payment_transactions.terminal_id IS '단말기 ID';
COMMENT ON COLUMN bms.payment_transactions.transaction_status IS '거래 상태';
COMMENT ON COLUMN bms.payment_transactions.failure_reason IS '실패 사유';
COMMENT ON COLUMN bms.payment_transactions.retry_count IS '재시도 횟수';
COMMENT ON COLUMN bms.payment_transactions.gateway_response IS '게이트웨이 응답 (JSON)';
COMMENT ON COLUMN bms.payment_transactions.receipt_number IS '영수증 번호';
COMMENT ON COLUMN bms.payment_transactions.receipt_url IS '영수증 URL';
COMMENT ON COLUMN bms.payment_transactions.reconciliation_status IS '대사 상태';
COMMENT ON COLUMN bms.payment_transactions.reconciled_at IS '대사 완료 일시';
COMMENT ON COLUMN bms.payment_transactions.settlement_date IS '정산일';
COMMENT ON COLUMN bms.payment_transactions.notes IS '비고';
COMMENT ON COLUMN bms.payment_transactions.created_at IS '생성 일시';
COMMENT ON COLUMN bms.payment_transactions.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.payment_transactions.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.payment_transactions.updated_by IS '수정자 사용자 ID';

-- 유지보수 작업 실행 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.maintenance_task_executions.execution_id IS '실행 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.maintenance_task_executions.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.maintenance_task_executions.task_id IS '작업 식별자 (UUID)';
COMMENT ON COLUMN bms.maintenance_task_executions.asset_id IS '시설 자산 식별자 (UUID)';
COMMENT ON COLUMN bms.maintenance_task_executions.execution_number IS '실행 번호';
COMMENT ON COLUMN bms.maintenance_task_executions.scheduled_date IS '예정일';
COMMENT ON COLUMN bms.maintenance_task_executions.actual_start_date IS '실제 시작일';
COMMENT ON COLUMN bms.maintenance_task_executions.actual_end_date IS '실제 종료일';
COMMENT ON COLUMN bms.maintenance_task_executions.duration_hours IS '소요 시간 (시간)';
COMMENT ON COLUMN bms.maintenance_task_executions.technician_id IS '기술자 사용자 ID';
COMMENT ON COLUMN bms.maintenance_task_executions.contractor_id IS '협력업체 식별자 (UUID, 선택사항)';
COMMENT ON COLUMN bms.maintenance_task_executions.execution_status IS '실행 상태';
COMMENT ON COLUMN bms.maintenance_task_executions.work_description IS '작업 설명';
COMMENT ON COLUMN bms.maintenance_task_executions.materials_used IS '사용 자재 (JSON)';
COMMENT ON COLUMN bms.maintenance_task_executions.tools_required IS '필요 도구 (JSON)';
COMMENT ON COLUMN bms.maintenance_task_executions.safety_precautions IS '안전 주의사항';
COMMENT ON COLUMN bms.maintenance_task_executions.quality_check IS '품질 검사 결과';
COMMENT ON COLUMN bms.maintenance_task_executions.completion_notes IS '완료 메모';
COMMENT ON COLUMN bms.maintenance_task_executions.issues_encountered IS '발생한 문제점';
COMMENT ON COLUMN bms.maintenance_task_executions.recommendations IS '권고사항';
COMMENT ON COLUMN bms.maintenance_task_executions.follow_up_required IS '후속 조치 필요 여부';
COMMENT ON COLUMN bms.maintenance_task_executions.next_maintenance_date IS '다음 유지보수 예정일';
COMMENT ON COLUMN bms.maintenance_task_executions.cost_estimate IS '예상 비용';
COMMENT ON COLUMN bms.maintenance_task_executions.actual_cost IS '실제 비용';
COMMENT ON COLUMN bms.maintenance_task_executions.labor_cost IS '인건비';
COMMENT ON COLUMN bms.maintenance_task_executions.material_cost IS '자재비';
COMMENT ON COLUMN bms.maintenance_task_executions.equipment_cost IS '장비비';
COMMENT ON COLUMN bms.maintenance_task_executions.photos IS '작업 사진';
COMMENT ON COLUMN bms.maintenance_task_executions.documents IS '관련 문서';
COMMENT ON COLUMN bms.maintenance_task_executions.warranty_period IS '보증 기간 (일)';
COMMENT ON COLUMN bms.maintenance_task_executions.approved_by IS '승인자 사용자 ID';
COMMENT ON COLUMN bms.maintenance_task_executions.approved_at IS '승인 일시';
COMMENT ON COLUMN bms.maintenance_task_executions.created_at IS '생성 일시';
COMMENT ON COLUMN bms.maintenance_task_executions.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.maintenance_task_executions.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.maintenance_task_executions.updated_by IS '수정자 사용자 ID';

-- 외주 작업 할당 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.outsourcing_work_assignments.assignment_id IS '할당 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.outsourcing_work_assignments.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.outsourcing_work_assignments.request_id IS '작업 요청 식별자 (UUID)';
COMMENT ON COLUMN bms.outsourcing_work_assignments.contractor_id IS '협력업체 식별자 (UUID)';
COMMENT ON COLUMN bms.outsourcing_work_assignments.assignment_number IS '할당 번호';
COMMENT ON COLUMN bms.outsourcing_work_assignments.assignment_date IS '할당일';
COMMENT ON COLUMN bms.outsourcing_work_assignments.work_description IS '작업 설명';
COMMENT ON COLUMN bms.outsourcing_work_assignments.work_scope IS '작업 범위';
COMMENT ON COLUMN bms.outsourcing_work_assignments.priority_level IS '우선순위';
COMMENT ON COLUMN bms.outsourcing_work_assignments.scheduled_start_date IS '예정 시작일';
COMMENT ON COLUMN bms.outsourcing_work_assignments.scheduled_end_date IS '예정 완료일';
COMMENT ON COLUMN bms.outsourcing_work_assignments.estimated_duration IS '예상 소요 시간 (시간)';
COMMENT ON COLUMN bms.outsourcing_work_assignments.estimated_cost IS '예상 비용';
COMMENT ON COLUMN bms.outsourcing_work_assignments.contract_terms IS '계약 조건';
COMMENT ON COLUMN bms.outsourcing_work_assignments.payment_terms IS '결제 조건';
COMMENT ON COLUMN bms.outsourcing_work_assignments.quality_requirements IS '품질 요구사항';
COMMENT ON COLUMN bms.outsourcing_work_assignments.safety_requirements IS '안전 요구사항';
COMMENT ON COLUMN bms.outsourcing_work_assignments.materials_provided IS '제공 자재 (JSON)';
COMMENT ON COLUMN bms.outsourcing_work_assignments.tools_provided IS '제공 도구 (JSON)';
COMMENT ON COLUMN bms.outsourcing_work_assignments.access_requirements IS '접근 요구사항';
COMMENT ON COLUMN bms.outsourcing_work_assignments.contact_person IS '담당자명';
COMMENT ON COLUMN bms.outsourcing_work_assignments.contact_phone IS '담당자 연락처';
COMMENT ON COLUMN bms.outsourcing_work_assignments.assignment_status IS '할당 상태';
COMMENT ON COLUMN bms.outsourcing_work_assignments.acceptance_date IS '수락일';
COMMENT ON COLUMN bms.outsourcing_work_assignments.rejection_reason IS '거부 사유';
COMMENT ON COLUMN bms.outsourcing_work_assignments.actual_start_date IS '실제 시작일';
COMMENT ON COLUMN bms.outsourcing_work_assignments.actual_end_date IS '실제 완료일';
COMMENT ON COLUMN bms.outsourcing_work_assignments.actual_duration IS '실제 소요 시간 (시간)';
COMMENT ON COLUMN bms.outsourcing_work_assignments.actual_cost IS '실제 비용';
COMMENT ON COLUMN bms.outsourcing_work_assignments.completion_report IS '완료 보고서';
COMMENT ON COLUMN bms.outsourcing_work_assignments.quality_rating IS '품질 평가';
COMMENT ON COLUMN bms.outsourcing_work_assignments.performance_rating IS '성과 평가';
COMMENT ON COLUMN bms.outsourcing_work_assignments.customer_satisfaction IS '고객 만족도';
COMMENT ON COLUMN bms.outsourcing_work_assignments.warranty_period IS '보증 기간 (일)';
COMMENT ON COLUMN bms.outsourcing_work_assignments.warranty_terms IS '보증 조건';
COMMENT ON COLUMN bms.outsourcing_work_assignments.invoice_submitted IS '송장 제출 여부';
COMMENT ON COLUMN bms.outsourcing_work_assignments.payment_status IS '결제 상태';
COMMENT ON COLUMN bms.outsourcing_work_assignments.notes IS '비고';
COMMENT ON COLUMN bms.outsourcing_work_assignments.created_at IS '생성 일시';
COMMENT ON COLUMN bms.outsourcing_work_assignments.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.outsourcing_work_assignments.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.outsourcing_work_assignments.updated_by IS '수정자 사용자 ID';

-- 유지보수 효과 분석 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.analysis_id IS '분석 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.asset_id IS '시설 자산 식별자 (UUID, 선택사항)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.analysis_period_start IS '분석 기간 시작일';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.analysis_period_end IS '분석 기간 종료일';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.analysis_type IS '분석 유형';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.total_maintenance_cost IS '총 유지보수 비용';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.preventive_cost IS '예방 유지보수 비용';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.corrective_cost IS '수정 유지보수 비용';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.emergency_cost IS '응급 수리 비용';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.downtime_hours IS '가동 중단 시간 (시간)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.downtime_cost IS '가동 중단 비용';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.availability_rate IS '가용률 (%)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.reliability_rate IS '신뢰성 (%)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.mtbf IS '평균 고장 간격 (시간)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.mttr IS '평균 수리 시간 (시간)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.failure_count IS '고장 횟수';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.repair_count IS '수리 횟수';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.maintenance_count IS '유지보수 횟수';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.cost_per_hour IS '시간당 비용';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.cost_per_failure IS '고장당 비용';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.roi_percentage IS '투자 수익률 (%)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.cost_savings IS '비용 절감액';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.efficiency_improvement IS '효율성 개선 (%)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.quality_score IS '품질 점수';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.customer_satisfaction IS '고객 만족도';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.recommendations IS '권고사항 (JSON)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.improvement_actions IS '개선 조치 (JSON)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.benchmark_comparison IS '벤치마크 비교 (JSON)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.trend_analysis IS '트렌드 분석 (JSON)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.risk_assessment IS '위험 평가 (JSON)';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.next_review_date IS '다음 검토 예정일';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.analyst_id IS '분석자 사용자 ID';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.approved_by IS '승인자 사용자 ID';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.approved_at IS '승인 일시';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.created_at IS '생성 일시';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.maintenance_effectiveness_analysis.updated_by IS '수정자 사용자 ID';