-- =====================================================
-- 모든 컬럼 자동 한글 커멘트 생성 스크립트 (1부)
-- 컬럼명 패턴을 기반으로 의미있는 한글 커멘트 자동 생성
-- =====================================================

-- 작업 보증 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.work_warranties.warranty_id IS '보증 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.work_warranties.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.work_warranties.work_order_id IS '작업 지시 식별자 (UUID)';
COMMENT ON COLUMN bms.work_warranties.contractor_id IS '협력업체 식별자 (UUID)';
COMMENT ON COLUMN bms.work_warranties.warranty_number IS '보증 번호';
COMMENT ON COLUMN bms.work_warranties.warranty_type IS '보증 유형';
COMMENT ON COLUMN bms.work_warranties.warranty_description IS '보증 설명';
COMMENT ON COLUMN bms.work_warranties.warranty_start_date IS '보증 시작일';
COMMENT ON COLUMN bms.work_warranties.warranty_end_date IS '보증 종료일';
COMMENT ON COLUMN bms.work_warranties.warranty_period_days IS '보증 기간 (일)';
COMMENT ON COLUMN bms.work_warranties.warranty_terms IS '보증 조건';
COMMENT ON COLUMN bms.work_warranties.coverage_scope IS '보증 범위';
COMMENT ON COLUMN bms.work_warranties.exclusions IS '보증 제외 사항';
COMMENT ON COLUMN bms.work_warranties.warranty_status IS '보증 상태';
COMMENT ON COLUMN bms.work_warranties.claim_procedure IS '클레임 절차';
COMMENT ON COLUMN bms.work_warranties.contact_information IS '연락처 정보';
COMMENT ON COLUMN bms.work_warranties.warranty_document_path IS '보증서 문서 경로';
COMMENT ON COLUMN bms.work_warranties.is_transferable IS '양도 가능 여부';
COMMENT ON COLUMN bms.work_warranties.transfer_conditions IS '양도 조건';
COMMENT ON COLUMN bms.work_warranties.maintenance_requirements IS '유지보수 요구사항';
COMMENT ON COLUMN bms.work_warranties.inspection_schedule IS '점검 일정';
COMMENT ON COLUMN bms.work_warranties.renewal_options IS '갱신 옵션';
COMMENT ON COLUMN bms.work_warranties.cost_coverage IS '비용 보장 범위';
COMMENT ON COLUMN bms.work_warranties.labor_coverage IS '인건비 보장 여부';
COMMENT ON COLUMN bms.work_warranties.parts_coverage IS '부품 보장 여부';
COMMENT ON COLUMN bms.work_warranties.response_time_hours IS '응답 시간 (시간)';
COMMENT ON COLUMN bms.work_warranties.resolution_time_hours IS '해결 시간 (시간)';
COMMENT ON COLUMN bms.work_warranties.warranty_provider IS '보증 제공자';
COMMENT ON COLUMN bms.work_warranties.insurance_backing IS '보험 지원 여부';
COMMENT ON COLUMN bms.work_warranties.legal_jurisdiction IS '법적 관할권';
COMMENT ON COLUMN bms.work_warranties.dispute_resolution IS '분쟁 해결 방법';
COMMENT ON COLUMN bms.work_warranties.notification_requirements IS '통지 요구사항';
COMMENT ON COLUMN bms.work_warranties.documentation_requirements IS '문서화 요구사항';
COMMENT ON COLUMN bms.work_warranties.performance_standards IS '성능 기준';
COMMENT ON COLUMN bms.work_warranties.quality_metrics IS '품질 지표';
COMMENT ON COLUMN bms.work_warranties.compliance_requirements IS '준수 요구사항';
COMMENT ON COLUMN bms.work_warranties.environmental_conditions IS '환경 조건';
COMMENT ON COLUMN bms.work_warranties.usage_limitations IS '사용 제한사항';
COMMENT ON COLUMN bms.work_warranties.created_at IS '생성 일시';
COMMENT ON COLUMN bms.work_warranties.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.work_warranties.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.work_warranties.updated_by IS '수정자 사용자 ID';

-- 사용자 활동 로그 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.user_activity_logs.log_id IS '로그 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.user_activity_logs.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.user_activity_logs.user_id IS '사용자 식별자 (UUID)';
COMMENT ON COLUMN bms.user_activity_logs.session_id IS '세션 식별자';
COMMENT ON COLUMN bms.user_activity_logs.activity_type IS '활동 유형';
COMMENT ON COLUMN bms.user_activity_logs.activity_category IS '활동 분류';
COMMENT ON COLUMN bms.user_activity_logs.activity_description IS '활동 설명';
COMMENT ON COLUMN bms.user_activity_logs.resource_type IS '리소스 유형';
COMMENT ON COLUMN bms.user_activity_logs.resource_id IS '리소스 식별자';
COMMENT ON COLUMN bms.user_activity_logs.action_performed IS '수행된 액션';
COMMENT ON COLUMN bms.user_activity_logs.request_method IS '요청 메소드';
COMMENT ON COLUMN bms.user_activity_logs.request_url IS '요청 URL';
COMMENT ON COLUMN bms.user_activity_logs.request_parameters IS '요청 매개변수 (JSON)';
COMMENT ON COLUMN bms.user_activity_logs.response_status IS '응답 상태';
COMMENT ON COLUMN bms.user_activity_logs.response_time_ms IS '응답 시간 (밀리초)';
COMMENT ON COLUMN bms.user_activity_logs.ip_address IS 'IP 주소';
COMMENT ON COLUMN bms.user_activity_logs.user_agent IS '사용자 에이전트';
COMMENT ON COLUMN bms.user_activity_logs.device_type IS '디바이스 유형';
COMMENT ON COLUMN bms.user_activity_logs.browser_info IS '브라우저 정보';
COMMENT ON COLUMN bms.user_activity_logs.operating_system IS '운영체제';
COMMENT ON COLUMN bms.user_activity_logs.location_info IS '위치 정보 (JSON)';
COMMENT ON COLUMN bms.user_activity_logs.referrer_url IS '참조 URL';
COMMENT ON COLUMN bms.user_activity_logs.success_flag IS '성공 여부';
COMMENT ON COLUMN bms.user_activity_logs.error_message IS '오류 메시지';
COMMENT ON COLUMN bms.user_activity_logs.error_code IS '오류 코드';
COMMENT ON COLUMN bms.user_activity_logs.stack_trace IS '스택 트레이스';
COMMENT ON COLUMN bms.user_activity_logs.additional_data IS '추가 데이터 (JSON)';
COMMENT ON COLUMN bms.user_activity_logs.security_level IS '보안 수준';
COMMENT ON COLUMN bms.user_activity_logs.risk_score IS '위험 점수';
COMMENT ON COLUMN bms.user_activity_logs.anomaly_detected IS '이상 감지 여부';
COMMENT ON COLUMN bms.user_activity_logs.compliance_flags IS '준수 플래그 (JSON)';
COMMENT ON COLUMN bms.user_activity_logs.retention_period IS '보존 기간 (일)';
COMMENT ON COLUMN bms.user_activity_logs.archived_flag IS '아카이브 여부';
COMMENT ON COLUMN bms.user_activity_logs.processed_flag IS '처리 완료 여부';
COMMENT ON COLUMN bms.user_activity_logs.correlation_id IS '상관관계 식별자';
COMMENT ON COLUMN bms.user_activity_logs.parent_log_id IS '상위 로그 식별자 (UUID)';
COMMENT ON COLUMN bms.user_activity_logs.trace_id IS '추적 식별자';
COMMENT ON COLUMN bms.user_activity_logs.span_id IS '스팬 식별자';
COMMENT ON COLUMN bms.user_activity_logs.created_at IS '생성 일시';
COMMENT ON COLUMN bms.user_activity_logs.updated_at IS '수정 일시';

-- 점검 일정 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.inspection_schedules.schedule_id IS '일정 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.inspection_schedules.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.inspection_schedules.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.inspection_schedules.asset_id IS '시설 자산 식별자 (UUID)';
COMMENT ON COLUMN bms.inspection_schedules.template_id IS '템플릿 식별자 (UUID)';
COMMENT ON COLUMN bms.inspection_schedules.schedule_name IS '일정명';
COMMENT ON COLUMN bms.inspection_schedules.inspection_type IS '점검 유형';
COMMENT ON COLUMN bms.inspection_schedules.inspection_category IS '점검 분류';
COMMENT ON COLUMN bms.inspection_schedules.priority_level IS '우선순위';
COMMENT ON COLUMN bms.inspection_schedules.frequency_type IS '주기 유형';
COMMENT ON COLUMN bms.inspection_schedules.frequency_value IS '주기 값';
COMMENT ON COLUMN bms.inspection_schedules.frequency_unit IS '주기 단위';
COMMENT ON COLUMN bms.inspection_schedules.start_date IS '시작일';
COMMENT ON COLUMN bms.inspection_schedules.end_date IS '종료일';
COMMENT ON COLUMN bms.inspection_schedules.next_inspection_date IS '다음 점검일';
COMMENT ON COLUMN bms.inspection_schedules.last_inspection_date IS '마지막 점검일';
COMMENT ON COLUMN bms.inspection_schedules.scheduled_time IS '예정 시간';
COMMENT ON COLUMN bms.inspection_schedules.estimated_duration IS '예상 소요 시간 (분)';
COMMENT ON COLUMN bms.inspection_schedules.assigned_inspector IS '배정된 점검자 사용자 ID';
COMMENT ON COLUMN bms.inspection_schedules.backup_inspector IS '백업 점검자 사용자 ID';
COMMENT ON COLUMN bms.inspection_schedules.contractor_id IS '협력업체 식별자 (UUID)';
COMMENT ON COLUMN bms.inspection_schedules.inspection_scope IS '점검 범위';
COMMENT ON COLUMN bms.inspection_schedules.required_tools IS '필요 도구 (JSON)';
COMMENT ON COLUMN bms.inspection_schedules.safety_requirements IS '안전 요구사항';
COMMENT ON COLUMN bms.inspection_schedules.access_requirements IS '접근 요구사항';
COMMENT ON COLUMN bms.inspection_schedules.weather_dependency IS '날씨 의존성';
COMMENT ON COLUMN bms.inspection_schedules.seasonal_adjustments IS '계절별 조정사항';
COMMENT ON COLUMN bms.inspection_schedules.compliance_standards IS '준수 기준';
COMMENT ON COLUMN bms.inspection_schedules.regulatory_requirements IS '규제 요구사항';
COMMENT ON COLUMN bms.inspection_schedules.documentation_requirements IS '문서화 요구사항';
COMMENT ON COLUMN bms.inspection_schedules.notification_settings IS '알림 설정 (JSON)';
COMMENT ON COLUMN bms.inspection_schedules.reminder_schedule IS '리마인더 일정';
COMMENT ON COLUMN bms.inspection_schedules.escalation_rules IS '에스컬레이션 규칙 (JSON)';
COMMENT ON COLUMN bms.inspection_schedules.cost_estimate IS '예상 비용';
COMMENT ON COLUMN bms.inspection_schedules.budget_allocation IS '예산 할당';
COMMENT ON COLUMN bms.inspection_schedules.schedule_status IS '일정 상태';
COMMENT ON COLUMN bms.inspection_schedules.is_active IS '활성 상태';
COMMENT ON COLUMN bms.inspection_schedules.is_recurring IS '반복 여부';
COMMENT ON COLUMN bms.inspection_schedules.auto_reschedule IS '자동 재일정 여부';
COMMENT ON COLUMN bms.inspection_schedules.created_at IS '생성 일시';
COMMENT ON COLUMN bms.inspection_schedules.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.inspection_schedules.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.inspection_schedules.updated_by IS '수정자 사용자 ID';

-- 분쟁 사건 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.dispute_cases.case_id IS '사건 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.dispute_cases.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.dispute_cases.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.dispute_cases.unit_id IS '세대 식별자 (UUID)';
COMMENT ON COLUMN bms.dispute_cases.case_number IS '사건 번호';
COMMENT ON COLUMN bms.dispute_cases.case_type IS '사건 유형';
COMMENT ON COLUMN bms.dispute_cases.dispute_category IS '분쟁 분류';
COMMENT ON COLUMN bms.dispute_cases.case_title IS '사건 제목';
COMMENT ON COLUMN bms.dispute_cases.case_description IS '사건 설명';
COMMENT ON COLUMN bms.dispute_cases.plaintiff_name IS '원고명';
COMMENT ON COLUMN bms.dispute_cases.plaintiff_contact IS '원고 연락처';
COMMENT ON COLUMN bms.dispute_cases.defendant_name IS '피고명';
COMMENT ON COLUMN bms.dispute_cases.defendant_contact IS '피고 연락처';
COMMENT ON COLUMN bms.dispute_cases.case_status IS '사건 상태';
COMMENT ON COLUMN bms.dispute_cases.priority_level IS '우선순위';
COMMENT ON COLUMN bms.dispute_cases.filing_date IS '접수일';
COMMENT ON COLUMN bms.dispute_cases.response_due_date IS '답변 기한';
COMMENT ON COLUMN bms.dispute_cases.hearing_date IS '심리일';
COMMENT ON COLUMN bms.dispute_cases.resolution_date IS '해결일';
COMMENT ON COLUMN bms.dispute_cases.dispute_amount IS '분쟁 금액';
COMMENT ON COLUMN bms.dispute_cases.claimed_amount IS '청구 금액';
COMMENT ON COLUMN bms.dispute_cases.settlement_amount IS '합의 금액';
COMMENT ON COLUMN bms.dispute_cases.legal_representative IS '법정 대리인';
COMMENT ON COLUMN bms.dispute_cases.assigned_lawyer IS '배정 변호사';
COMMENT ON COLUMN bms.dispute_cases.court_name IS '법원명';
COMMENT ON COLUMN bms.dispute_cases.case_reference IS '사건 참조번호';
COMMENT ON COLUMN bms.dispute_cases.jurisdiction IS '관할권';
COMMENT ON COLUMN bms.dispute_cases.applicable_law IS '적용 법률';
COMMENT ON COLUMN bms.dispute_cases.evidence_summary IS '증거 요약';
COMMENT ON COLUMN bms.dispute_cases.witness_list IS '증인 목록 (JSON)';
COMMENT ON COLUMN bms.dispute_cases.document_list IS '문서 목록 (JSON)';
COMMENT ON COLUMN bms.dispute_cases.mediation_attempts IS '조정 시도 횟수';
COMMENT ON COLUMN bms.dispute_cases.mediation_outcome IS '조정 결과';
COMMENT ON COLUMN bms.dispute_cases.arbitration_clause IS '중재 조항';
COMMENT ON COLUMN bms.dispute_cases.insurance_coverage IS '보험 적용 여부';
COMMENT ON COLUMN bms.dispute_cases.insurance_claim_number IS '보험 청구 번호';
COMMENT ON COLUMN bms.dispute_cases.legal_costs IS '법무 비용';
COMMENT ON COLUMN bms.dispute_cases.court_fees IS '법원 수수료';
COMMENT ON COLUMN bms.dispute_cases.expert_fees IS '전문가 수수료';
COMMENT ON COLUMN bms.dispute_cases.total_costs IS '총 비용';
COMMENT ON COLUMN bms.dispute_cases.cost_recovery IS '비용 회수 여부';
COMMENT ON COLUMN bms.dispute_cases.final_judgment IS '최종 판결';
COMMENT ON COLUMN bms.dispute_cases.appeal_status IS '항소 상태';
COMMENT ON COLUMN bms.dispute_cases.enforcement_status IS '집행 상태';
COMMENT ON COLUMN bms.dispute_cases.created_at IS '생성 일시';
COMMENT ON COLUMN bms.dispute_cases.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.dispute_cases.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.dispute_cases.updated_by IS '수정자 사용자 ID';

-- 회사 테이블 추가 컬럼 커멘트 (커멘트가 없는 컬럼들)
COMMENT ON COLUMN bms.companies.company_id IS '회사 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.companies.company_name IS '회사명';
COMMENT ON COLUMN bms.companies.representative_name IS '대표자명';
COMMENT ON COLUMN bms.companies.business_address IS '사업장 주소';
COMMENT ON COLUMN bms.companies.contact_phone IS '연락처 전화번호';
COMMENT ON COLUMN bms.companies.contact_email IS '연락처 이메일';
COMMENT ON COLUMN bms.companies.business_type IS '사업 유형';
COMMENT ON COLUMN bms.companies.establishment_date IS '설립일';
COMMENT ON COLUMN bms.companies.verification_date IS '검증일';
COMMENT ON COLUMN bms.companies.verification_data IS '검증 데이터 (JSON)';
COMMENT ON COLUMN bms.companies.subscription_plan IS '구독 플랜';
COMMENT ON COLUMN bms.companies.subscription_start_date IS '구독 시작일';
COMMENT ON COLUMN bms.companies.subscription_end_date IS '구독 종료일';
COMMENT ON COLUMN bms.companies.created_at IS '생성 일시';
COMMENT ON COLUMN bms.companies.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.companies.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.companies.updated_by IS '수정자 사용자 ID';

-- 자재 테이블 추가 컬럼 커멘트 (커멘트가 없는 컬럼들)
COMMENT ON COLUMN bms.materials.material_description IS '자재 설명';
COMMENT ON COLUMN bms.materials.material_type IS '자재 유형';
COMMENT ON COLUMN bms.materials.material_group IS '자재 그룹';
COMMENT ON COLUMN bms.materials.brand IS '브랜드';
COMMENT ON COLUMN bms.materials.model_number IS '모델 번호';
COMMENT ON COLUMN bms.materials.part_number IS '부품 번호';
COMMENT ON COLUMN bms.materials.dimensions IS '치수 정보 (JSON)';
COMMENT ON COLUMN bms.materials.weight IS '중량';
COMMENT ON COLUMN bms.materials.color IS '색상';
COMMENT ON COLUMN bms.materials.material_composition IS '자재 구성';
COMMENT ON COLUMN bms.materials.base_unit_id IS '기본 단위 식별자 (UUID)';
COMMENT ON COLUMN bms.materials.purchase_unit_id IS '구매 단위 식별자 (UUID)';
COMMENT ON COLUMN bms.materials.stock_unit_id IS '재고 단위 식별자 (UUID)';
COMMENT ON COLUMN bms.materials.standard_cost IS '표준 비용';
COMMENT ON COLUMN bms.materials.last_purchase_cost IS '최종 구매 비용';
COMMENT ON COLUMN bms.materials.average_cost IS '평균 비용';
COMMENT ON COLUMN bms.materials.list_price IS '정가';
COMMENT ON COLUMN bms.materials.track_inventory IS '재고 추적 여부';
COMMENT ON COLUMN bms.materials.reorder_quantity IS '재주문 수량';
COMMENT ON COLUMN bms.materials.quality_grade IS '품질 등급';