-- =====================================================
-- 모든 컬럼 한글 커멘트 추가 스크립트 (Part 2)
-- 나머지 테이블들의 모든 컬럼에 한글 커멘트 추가
-- =====================================================

-- 작업 지시 테이블 추가 컬럼 커멘트 (커멘트가 없는 컬럼들)
COMMENT ON COLUMN bms.work_orders.work_order_id IS '작업 지시 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.work_orders.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.work_orders.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.work_orders.unit_id IS '세대 식별자 (UUID)';
COMMENT ON COLUMN bms.work_orders.asset_id IS '시설 자산 식별자 (UUID)';
COMMENT ON COLUMN bms.work_orders.fault_report_id IS '고장 신고 식별자 (UUID)';
COMMENT ON COLUMN bms.work_orders.work_order_number IS '작업 지시 번호';
COMMENT ON COLUMN bms.work_orders.work_type IS '작업 유형';
COMMENT ON COLUMN bms.work_orders.work_category IS '작업 분류';
COMMENT ON COLUMN bms.work_orders.priority_level IS '우선순위';
COMMENT ON COLUMN bms.work_orders.work_title IS '작업 제목';
COMMENT ON COLUMN bms.work_orders.work_description IS '작업 설명';
COMMENT ON COLUMN bms.work_orders.requested_by IS '요청자 사용자 ID';
COMMENT ON COLUMN bms.work_orders.assigned_to IS '담당자 사용자 ID';
COMMENT ON COLUMN bms.work_orders.contractor_id IS '협력업체 식별자 (UUID)';
COMMENT ON COLUMN bms.work_orders.work_status IS '작업 상태';
COMMENT ON COLUMN bms.work_orders.scheduled_start_date IS '예정 시작일';
COMMENT ON COLUMN bms.work_orders.scheduled_end_date IS '예정 종료일';
COMMENT ON COLUMN bms.work_orders.actual_start_date IS '실제 시작일';
COMMENT ON COLUMN bms.work_orders.actual_end_date IS '실제 종료일';
COMMENT ON COLUMN bms.work_orders.estimated_hours IS '예상 작업 시간';
COMMENT ON COLUMN bms.work_orders.actual_hours IS '실제 작업 시간';
COMMENT ON COLUMN bms.work_orders.estimated_cost IS '예상 비용';
COMMENT ON COLUMN bms.work_orders.actual_cost IS '실제 비용';
COMMENT ON COLUMN bms.work_orders.labor_cost IS '인건비';
COMMENT ON COLUMN bms.work_orders.material_cost IS '자재비';
COMMENT ON COLUMN bms.work_orders.equipment_cost IS '장비비';
COMMENT ON COLUMN bms.work_orders.other_costs IS '기타 비용';
COMMENT ON COLUMN bms.work_orders.work_location IS '작업 위치';
COMMENT ON COLUMN bms.work_orders.access_requirements IS '접근 요구사항';
COMMENT ON COLUMN bms.work_orders.safety_requirements IS '안전 요구사항';
COMMENT ON COLUMN bms.work_orders.required_skills IS '필요 기술 (JSON)';
COMMENT ON COLUMN bms.work_orders.required_tools IS '필요 도구 (JSON)';
COMMENT ON COLUMN bms.work_orders.required_materials IS '필요 자재 (JSON)';
COMMENT ON COLUMN bms.work_orders.work_instructions IS '작업 지시사항';
COMMENT ON COLUMN bms.work_orders.quality_standards IS '품질 기준';
COMMENT ON COLUMN bms.work_orders.completion_criteria IS '완료 기준';
COMMENT ON COLUMN bms.work_orders.approval_required IS '승인 필요 여부';
COMMENT ON COLUMN bms.work_orders.approved_by IS '승인자 사용자 ID';
COMMENT ON COLUMN bms.work_orders.approved_at IS '승인 일시';
COMMENT ON COLUMN bms.work_orders.work_notes IS '작업 메모';
COMMENT ON COLUMN bms.work_orders.completion_notes IS '완료 메모';
COMMENT ON COLUMN bms.work_orders.customer_satisfaction IS '고객 만족도';
COMMENT ON COLUMN bms.work_orders.follow_up_required IS '후속 조치 필요 여부';
COMMENT ON COLUMN bms.work_orders.follow_up_date IS '후속 조치일';
COMMENT ON COLUMN bms.work_orders.warranty_period IS '보증 기간 (일)';
COMMENT ON COLUMN bms.work_orders.warranty_start_date IS '보증 시작일';
COMMENT ON COLUMN bms.work_orders.warranty_end_date IS '보증 종료일';
COMMENT ON COLUMN bms.work_orders.created_at IS '생성 일시';
COMMENT ON COLUMN bms.work_orders.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.work_orders.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.work_orders.updated_by IS '수정자 사용자 ID';

-- 고장 신고 테이블 추가 컬럼 커멘트 (커멘트가 없는 컬럼들)
COMMENT ON COLUMN bms.fault_reports.fault_report_id IS '고장 신고 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.fault_reports.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.fault_reports.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.fault_reports.unit_id IS '세대 식별자 (UUID)';
COMMENT ON COLUMN bms.fault_reports.asset_id IS '시설 자산 식별자 (UUID)';
COMMENT ON COLUMN bms.fault_reports.report_number IS '신고 번호';
COMMENT ON COLUMN bms.fault_reports.fault_type IS '고장 유형';
COMMENT ON COLUMN bms.fault_reports.fault_category IS '고장 분류';
COMMENT ON COLUMN bms.fault_reports.severity_level IS '심각도';
COMMENT ON COLUMN bms.fault_reports.priority_level IS '우선순위';
COMMENT ON COLUMN bms.fault_reports.fault_title IS '고장 제목';
COMMENT ON COLUMN bms.fault_reports.fault_description IS '고장 설명';
COMMENT ON COLUMN bms.fault_reports.reported_by IS '신고자 사용자 ID';
COMMENT ON COLUMN bms.fault_reports.reporter_name IS '신고자명';
COMMENT ON COLUMN bms.fault_reports.reporter_contact IS '신고자 연락처';
COMMENT ON COLUMN bms.fault_reports.report_date IS '신고일';
COMMENT ON COLUMN bms.fault_reports.occurrence_date IS '발생일';
COMMENT ON COLUMN bms.fault_reports.discovery_method IS '발견 방법';
COMMENT ON COLUMN bms.fault_reports.fault_location IS '고장 위치';
COMMENT ON COLUMN bms.fault_reports.environmental_conditions IS '환경 조건';
COMMENT ON COLUMN bms.fault_reports.weather_conditions IS '기상 조건';
COMMENT ON COLUMN bms.fault_reports.operating_conditions IS '운영 조건';
COMMENT ON COLUMN bms.fault_reports.symptoms_observed IS '관찰된 증상';
COMMENT ON COLUMN bms.fault_reports.error_codes IS '오류 코드 (JSON)';
COMMENT ON COLUMN bms.fault_reports.diagnostic_data IS '진단 데이터 (JSON)';
COMMENT ON COLUMN bms.fault_reports.photos IS '사진 경로 (JSON)';
COMMENT ON COLUMN bms.fault_reports.videos IS '동영상 경로 (JSON)';
COMMENT ON COLUMN bms.fault_reports.audio_recordings IS '음성 녹음 경로 (JSON)';
COMMENT ON COLUMN bms.fault_reports.documents IS '관련 문서 (JSON)';
COMMENT ON COLUMN bms.fault_reports.immediate_actions IS '즉시 조치사항';
COMMENT ON COLUMN bms.fault_reports.safety_concerns IS '안전 우려사항';
COMMENT ON COLUMN bms.fault_reports.impact_assessment IS '영향 평가';
COMMENT ON COLUMN bms.fault_reports.business_impact IS '업무 영향도';
COMMENT ON COLUMN bms.fault_reports.estimated_downtime IS '예상 중단 시간 (분)';
COMMENT ON COLUMN bms.fault_reports.actual_downtime IS '실제 중단 시간 (분)';
COMMENT ON COLUMN bms.fault_reports.cost_estimate IS '예상 비용';
COMMENT ON COLUMN bms.fault_reports.assigned_technician IS '배정 기술자 사용자 ID';
COMMENT ON COLUMN bms.fault_reports.contractor_id IS '협력업체 식별자 (UUID)';
COMMENT ON COLUMN bms.fault_reports.report_status IS '신고 상태';
COMMENT ON COLUMN bms.fault_reports.resolution_status IS '해결 상태';
COMMENT ON COLUMN bms.fault_reports.escalation_level IS '에스컬레이션 레벨';
COMMENT ON COLUMN bms.fault_reports.escalated_to IS '에스컬레이션 대상 사용자 ID';
COMMENT ON COLUMN bms.fault_reports.escalation_date IS '에스컬레이션 일시';
COMMENT ON COLUMN bms.fault_reports.response_time_minutes IS '응답 시간 (분)';
COMMENT ON COLUMN bms.fault_reports.resolution_time_minutes IS '해결 시간 (분)';
COMMENT ON COLUMN bms.fault_reports.sla_compliance IS 'SLA 준수 여부';
COMMENT ON COLUMN bms.fault_reports.customer_notification IS '고객 알림 여부';
COMMENT ON COLUMN bms.fault_reports.notification_method IS '알림 방법';
COMMENT ON COLUMN bms.fault_reports.follow_up_required IS '후속 조치 필요 여부';
COMMENT ON COLUMN bms.fault_reports.follow_up_date IS '후속 조치일';
COMMENT ON COLUMN bms.fault_reports.created_at IS '생성 일시';
COMMENT ON COLUMN bms.fault_reports.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.fault_reports.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.fault_reports.updated_by IS '수정자 사용자 ID';

-- 예방 정비 실행 테이블 추가 컬럼 커멘트 (커멘트가 없는 컬럼들)
COMMENT ON COLUMN bms.preventive_maintenance_executions.execution_id IS '실행 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.asset_id IS '시설 자산 식별자 (UUID)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.schedule_id IS '일정 식별자 (UUID)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.template_id IS '템플릿 식별자 (UUID)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.execution_number IS '실행 번호';
COMMENT ON COLUMN bms.preventive_maintenance_executions.maintenance_type IS '정비 유형';
COMMENT ON COLUMN bms.preventive_maintenance_executions.maintenance_category IS '정비 분류';
COMMENT ON COLUMN bms.preventive_maintenance_executions.priority_level IS '우선순위';
COMMENT ON COLUMN bms.preventive_maintenance_executions.scheduled_date IS '예정일';
COMMENT ON COLUMN bms.preventive_maintenance_executions.actual_start_date IS '실제 시작일';
COMMENT ON COLUMN bms.preventive_maintenance_executions.actual_end_date IS '실제 종료일';
COMMENT ON COLUMN bms.preventive_maintenance_executions.estimated_duration IS '예상 소요 시간 (분)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.actual_duration IS '실제 소요 시간 (분)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.assigned_technician IS '배정 기술자 사용자 ID';
COMMENT ON COLUMN bms.preventive_maintenance_executions.backup_technician IS '백업 기술자 사용자 ID';
COMMENT ON COLUMN bms.preventive_maintenance_executions.contractor_id IS '협력업체 식별자 (UUID)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.execution_status IS '실행 상태';
COMMENT ON COLUMN bms.preventive_maintenance_executions.completion_percentage IS '완료율 (%)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.work_description IS '작업 설명';
COMMENT ON COLUMN bms.preventive_maintenance_executions.work_performed IS '수행된 작업';
COMMENT ON COLUMN bms.preventive_maintenance_executions.findings IS '발견사항';
COMMENT ON COLUMN bms.preventive_maintenance_executions.recommendations IS '권장사항';
COMMENT ON COLUMN bms.preventive_maintenance_executions.parts_used IS '사용된 부품 (JSON)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.materials_used IS '사용된 자재 (JSON)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.tools_used IS '사용된 도구 (JSON)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.labor_hours IS '작업 시간';
COMMENT ON COLUMN bms.preventive_maintenance_executions.labor_cost IS '인건비';
COMMENT ON COLUMN bms.preventive_maintenance_executions.material_cost IS '자재비';
COMMENT ON COLUMN bms.preventive_maintenance_executions.equipment_cost IS '장비비';
COMMENT ON COLUMN bms.preventive_maintenance_executions.total_cost IS '총 비용';
COMMENT ON COLUMN bms.preventive_maintenance_executions.quality_check_passed IS '품질 검사 통과 여부';
COMMENT ON COLUMN bms.preventive_maintenance_executions.quality_notes IS '품질 메모';
COMMENT ON COLUMN bms.preventive_maintenance_executions.safety_incidents IS '안전 사고 (JSON)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.environmental_impact IS '환경 영향';
COMMENT ON COLUMN bms.preventive_maintenance_executions.waste_generated IS '발생 폐기물 (JSON)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.energy_consumption IS '에너지 소비량';
COMMENT ON COLUMN bms.preventive_maintenance_executions.performance_metrics IS '성능 지표 (JSON)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.before_photos IS '작업 전 사진 (JSON)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.after_photos IS '작업 후 사진 (JSON)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.documentation IS '관련 문서 (JSON)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.customer_signature IS '고객 서명';
COMMENT ON COLUMN bms.preventive_maintenance_executions.technician_signature IS '기술자 서명';
COMMENT ON COLUMN bms.preventive_maintenance_executions.supervisor_approval IS '감독자 승인';
COMMENT ON COLUMN bms.preventive_maintenance_executions.next_maintenance_date IS '다음 정비일';
COMMENT ON COLUMN bms.preventive_maintenance_executions.warranty_period IS '보증 기간 (일)';
COMMENT ON COLUMN bms.preventive_maintenance_executions.follow_up_required IS '후속 조치 필요 여부';
COMMENT ON COLUMN bms.preventive_maintenance_executions.follow_up_date IS '후속 조치일';
COMMENT ON COLUMN bms.preventive_maintenance_executions.created_at IS '생성 일시';
COMMENT ON COLUMN bms.preventive_maintenance_executions.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.preventive_maintenance_executions.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.preventive_maintenance_executions.updated_by IS '수정자 사용자 ID';