-- =====================================================
-- 모든 컬럼 한글 커멘트 추가 스크립트 (Part 3)
-- 추가 테이블들의 모든 컬럼에 한글 커멘트 추가
-- =====================================================

-- 점검 실행 테이블 추가 컬럼 커멘트 (커멘트가 없는 컬럼들)
COMMENT ON COLUMN bms.inspection_executions.execution_id IS '실행 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.inspection_executions.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.inspection_executions.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.inspection_executions.asset_id IS '시설 자산 식별자 (UUID)';
COMMENT ON COLUMN bms.inspection_executions.schedule_id IS '일정 식별자 (UUID)';
COMMENT ON COLUMN bms.inspection_executions.template_id IS '템플릿 식별자 (UUID)';
COMMENT ON COLUMN bms.inspection_executions.execution_number IS '실행 번호';
COMMENT ON COLUMN bms.inspection_executions.inspection_type IS '점검 유형';
COMMENT ON COLUMN bms.inspection_executions.inspection_category IS '점검 분류';
COMMENT ON COLUMN bms.inspection_executions.priority_level IS '우선순위';
COMMENT ON COLUMN bms.inspection_executions.scheduled_date IS '예정일';
COMMENT ON COLUMN bms.inspection_executions.actual_start_date IS '실제 시작일';
COMMENT ON COLUMN bms.inspection_executions.actual_end_date IS '실제 종료일';
COMMENT ON COLUMN bms.inspection_executions.estimated_duration IS '예상 소요 시간 (분)';
COMMENT ON COLUMN bms.inspection_executions.actual_duration IS '실제 소요 시간 (분)';
COMMENT ON COLUMN bms.inspection_executions.assigned_inspector IS '배정 점검자 사용자 ID';
COMMENT ON COLUMN bms.inspection_executions.backup_inspector IS '백업 점검자 사용자 ID';
COMMENT ON COLUMN bms.inspection_executions.contractor_id IS '협력업체 식별자 (UUID)';
COMMENT ON COLUMN bms.inspection_executions.execution_status IS '실행 상태';
COMMENT ON COLUMN bms.inspection_executions.completion_percentage IS '완료율 (%)';
COMMENT ON COLUMN bms.inspection_executions.inspection_scope IS '점검 범위';
COMMENT ON COLUMN bms.inspection_executions.inspection_method IS '점검 방법';
COMMENT ON COLUMN bms.inspection_executions.inspection_criteria IS '점검 기준';
COMMENT ON COLUMN bms.inspection_executions.findings IS '발견사항';
COMMENT ON COLUMN bms.inspection_executions.defects_found IS '발견된 결함 (JSON)';
COMMENT ON COLUMN bms.inspection_executions.recommendations IS '권장사항';
COMMENT ON COLUMN bms.inspection_executions.corrective_actions IS '시정 조치사항';
COMMENT ON COLUMN bms.inspection_executions.follow_up_required IS '후속 조치 필요 여부';
COMMENT ON COLUMN bms.inspection_executions.follow_up_date IS '후속 조치일';
COMMENT ON COLUMN bms.inspection_executions.compliance_status IS '준수 상태';
COMMENT ON COLUMN bms.inspection_executions.regulatory_compliance IS '규제 준수 여부';
COMMENT ON COLUMN bms.inspection_executions.safety_compliance IS '안전 준수 여부';
COMMENT ON COLUMN bms.inspection_executions.quality_rating IS '품질 등급';
COMMENT ON COLUMN bms.inspection_executions.overall_condition IS '전반적 상태';
COMMENT ON COLUMN bms.inspection_executions.risk_assessment IS '위험 평가';
COMMENT ON COLUMN bms.inspection_executions.risk_level IS '위험 수준';
COMMENT ON COLUMN bms.inspection_executions.mitigation_measures IS '완화 조치';
COMMENT ON COLUMN bms.inspection_executions.tools_used IS '사용된 도구 (JSON)';
COMMENT ON COLUMN bms.inspection_executions.equipment_used IS '사용된 장비 (JSON)';
COMMENT ON COLUMN bms.inspection_executions.environmental_conditions IS '환경 조건';
COMMENT ON COLUMN bms.inspection_executions.weather_conditions IS '기상 조건';
COMMENT ON COLUMN bms.inspection_executions.temperature IS '온도';
COMMENT ON COLUMN bms.inspection_executions.humidity IS '습도';
COMMENT ON COLUMN bms.inspection_executions.before_photos IS '점검 전 사진 (JSON)';
COMMENT ON COLUMN bms.inspection_executions.during_photos IS '점검 중 사진 (JSON)';
COMMENT ON COLUMN bms.inspection_executions.after_photos IS '점검 후 사진 (JSON)';
COMMENT ON COLUMN bms.inspection_executions.documentation IS '관련 문서 (JSON)';
COMMENT ON COLUMN bms.inspection_executions.inspector_signature IS '점검자 서명';
COMMENT ON COLUMN bms.inspection_executions.supervisor_approval IS '감독자 승인';
COMMENT ON COLUMN bms.inspection_executions.customer_notification IS '고객 알림 여부';
COMMENT ON COLUMN bms.inspection_executions.next_inspection_date IS '다음 점검일';
COMMENT ON COLUMN bms.inspection_executions.created_at IS '생성 일시';
COMMENT ON COLUMN bms.inspection_executions.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.inspection_executions.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.inspection_executions.updated_by IS '수정자 사용자 ID';

-- 안전 사고 테이블 추가 컬럼 커멘트 (커멘트가 없는 컬럼들)
COMMENT ON COLUMN bms.safety_incidents.incident_id IS '사고 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.safety_incidents.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.safety_incidents.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.safety_incidents.unit_id IS '세대 식별자 (UUID)';
COMMENT ON COLUMN bms.safety_incidents.asset_id IS '시설 자산 식별자 (UUID)';
COMMENT ON COLUMN bms.safety_incidents.incident_number IS '사고 번호';
COMMENT ON COLUMN bms.safety_incidents.incident_type IS '사고 유형';
COMMENT ON COLUMN bms.safety_incidents.incident_category IS '사고 분류';
COMMENT ON COLUMN bms.safety_incidents.severity_level IS '심각도';
COMMENT ON COLUMN bms.safety_incidents.incident_title IS '사고 제목';
COMMENT ON COLUMN bms.safety_incidents.incident_description IS '사고 설명';
COMMENT ON COLUMN bms.safety_incidents.incident_date IS '사고 발생일';
COMMENT ON COLUMN bms.safety_incidents.incident_time IS '사고 발생 시간';
COMMENT ON COLUMN bms.safety_incidents.reported_date IS '신고일';
COMMENT ON COLUMN bms.safety_incidents.reported_by IS '신고자 사용자 ID';
COMMENT ON COLUMN bms.safety_incidents.reporter_name IS '신고자명';
COMMENT ON COLUMN bms.safety_incidents.reporter_contact IS '신고자 연락처';
COMMENT ON COLUMN bms.safety_incidents.incident_location IS '사고 위치';
COMMENT ON COLUMN bms.safety_incidents.location_details IS '위치 상세';
COMMENT ON COLUMN bms.safety_incidents.environmental_factors IS '환경 요인';
COMMENT ON COLUMN bms.safety_incidents.weather_conditions IS '기상 조건';
COMMENT ON COLUMN bms.safety_incidents.lighting_conditions IS '조명 조건';
COMMENT ON COLUMN bms.safety_incidents.surface_conditions IS '표면 조건';
COMMENT ON COLUMN bms.safety_incidents.people_involved IS '관련자 (JSON)';
COMMENT ON COLUMN bms.safety_incidents.injured_parties IS '부상자 (JSON)';
COMMENT ON COLUMN bms.safety_incidents.witnesses IS '목격자 (JSON)';
COMMENT ON COLUMN bms.safety_incidents.injury_type IS '부상 유형';
COMMENT ON COLUMN bms.safety_incidents.injury_severity IS '부상 심각도';
COMMENT ON COLUMN bms.safety_incidents.body_parts_affected IS '영향받은 신체 부위 (JSON)';
COMMENT ON COLUMN bms.safety_incidents.medical_attention_required IS '의료 조치 필요 여부';
COMMENT ON COLUMN bms.safety_incidents.medical_facility IS '의료 시설';
COMMENT ON COLUMN bms.safety_incidents.treatment_provided IS '제공된 치료';
COMMENT ON COLUMN bms.safety_incidents.hospitalization_required IS '입원 필요 여부';
COMMENT ON COLUMN bms.safety_incidents.days_away_from_work IS '업무 복귀까지 일수';
COMMENT ON COLUMN bms.safety_incidents.property_damage IS '재산 피해';
COMMENT ON COLUMN bms.safety_incidents.damage_cost IS '피해 비용';
COMMENT ON COLUMN bms.safety_incidents.equipment_involved IS '관련 장비 (JSON)';
COMMENT ON COLUMN bms.safety_incidents.materials_involved IS '관련 자재 (JSON)';
COMMENT ON COLUMN bms.safety_incidents.immediate_cause IS '직접 원인';
COMMENT ON COLUMN bms.safety_incidents.root_cause IS '근본 원인';
COMMENT ON COLUMN bms.safety_incidents.contributing_factors IS '기여 요인 (JSON)';
COMMENT ON COLUMN bms.safety_incidents.immediate_actions IS '즉시 조치사항';
COMMENT ON COLUMN bms.safety_incidents.corrective_actions IS '시정 조치사항';
COMMENT ON COLUMN bms.safety_incidents.preventive_measures IS '예방 조치사항';
COMMENT ON COLUMN bms.safety_incidents.investigation_status IS '조사 상태';
COMMENT ON COLUMN bms.safety_incidents.investigated_by IS '조사자 사용자 ID';
COMMENT ON COLUMN bms.safety_incidents.investigation_date IS '조사일';
COMMENT ON COLUMN bms.safety_incidents.investigation_findings IS '조사 결과';
COMMENT ON COLUMN bms.safety_incidents.lessons_learned IS '교훈';
COMMENT ON COLUMN bms.safety_incidents.training_required IS '교육 필요 여부';
COMMENT ON COLUMN bms.safety_incidents.policy_changes IS '정책 변경사항';
COMMENT ON COLUMN bms.safety_incidents.regulatory_notification IS '규제 기관 신고 여부';
COMMENT ON COLUMN bms.safety_incidents.insurance_claim IS '보험 청구 여부';
COMMENT ON COLUMN bms.safety_incidents.claim_number IS '청구 번호';
COMMENT ON COLUMN bms.safety_incidents.legal_action IS '법적 조치 여부';
COMMENT ON COLUMN bms.safety_incidents.created_at IS '생성 일시';
COMMENT ON COLUMN bms.safety_incidents.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.safety_incidents.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.safety_incidents.updated_by IS '수정자 사용자 ID';

-- 임차인 테이블 추가 컬럼 커멘트 (커멘트가 없는 컬럼들)
COMMENT ON COLUMN bms.tenants.tenant_id IS '임차인 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.tenants.company_id IS '회사 식별자 (UUID)';
COMMENT ON COLUMN bms.tenants.building_id IS '건물 식별자 (UUID)';
COMMENT ON COLUMN bms.tenants.unit_id IS '세대 식별자 (UUID)';
COMMENT ON COLUMN bms.tenants.tenant_number IS '임차인 번호';
COMMENT ON COLUMN bms.tenants.tenant_type IS '임차인 유형';
COMMENT ON COLUMN bms.tenants.tenant_status IS '임차인 상태';
COMMENT ON COLUMN bms.tenants.primary_tenant_name IS '주 임차인명';
COMMENT ON COLUMN bms.tenants.primary_tenant_phone IS '주 임차인 전화번호';
COMMENT ON COLUMN bms.tenants.primary_tenant_email IS '주 임차인 이메일';
COMMENT ON COLUMN bms.tenants.secondary_tenant_name IS '부 임차인명';
COMMENT ON COLUMN bms.tenants.secondary_tenant_phone IS '부 임차인 전화번호';
COMMENT ON COLUMN bms.tenants.secondary_tenant_email IS '부 임차인 이메일';
COMMENT ON COLUMN bms.tenants.emergency_contact_name IS '비상 연락처명';
COMMENT ON COLUMN bms.tenants.emergency_contact_phone IS '비상 연락처 전화번호';
COMMENT ON COLUMN bms.tenants.emergency_contact_relationship IS '비상 연락처 관계';
COMMENT ON COLUMN bms.tenants.identification_type IS '신분증 유형';
COMMENT ON COLUMN bms.tenants.identification_number IS '신분증 번호';
COMMENT ON COLUMN bms.tenants.date_of_birth IS '생년월일';
COMMENT ON COLUMN bms.tenants.nationality IS '국적';
COMMENT ON COLUMN bms.tenants.occupation IS '직업';
COMMENT ON COLUMN bms.tenants.employer IS '고용주';
COMMENT ON COLUMN bms.tenants.monthly_income IS '월 소득';
COMMENT ON COLUMN bms.tenants.credit_score IS '신용 점수';
COMMENT ON COLUMN bms.tenants.previous_address IS '이전 주소';
COMMENT ON COLUMN bms.tenants.previous_landlord IS '이전 임대인';
COMMENT ON COLUMN bms.tenants.previous_landlord_contact IS '이전 임대인 연락처';
COMMENT ON COLUMN bms.tenants.rental_history IS '임대 이력 (JSON)';
COMMENT ON COLUMN bms.tenants.references IS '추천인 (JSON)';
COMMENT ON COLUMN bms.tenants.background_check_status IS '신원 조회 상태';
COMMENT ON COLUMN bms.tenants.background_check_date IS '신원 조회일';
COMMENT ON COLUMN bms.tenants.move_in_date IS '입주일';
COMMENT ON COLUMN bms.tenants.move_out_date IS '퇴거일';
COMMENT ON COLUMN bms.tenants.lease_start_date IS '임대 시작일';
COMMENT ON COLUMN bms.tenants.lease_end_date IS '임대 종료일';
COMMENT ON COLUMN bms.tenants.lease_renewal_date IS '임대 갱신일';
COMMENT ON COLUMN bms.tenants.rent_amount IS '임대료';
COMMENT ON COLUMN bms.tenants.security_deposit IS '보증금';
COMMENT ON COLUMN bms.tenants.pet_deposit IS '반려동물 보증금';
COMMENT ON COLUMN bms.tenants.key_deposit IS '열쇠 보증금';
COMMENT ON COLUMN bms.tenants.utility_deposit IS '공과금 보증금';
COMMENT ON COLUMN bms.tenants.total_deposits IS '총 보증금';
COMMENT ON COLUMN bms.tenants.payment_method IS '결제 방법';
COMMENT ON COLUMN bms.tenants.bank_account IS '은행 계좌';
COMMENT ON COLUMN bms.tenants.auto_pay_enabled IS '자동 결제 활성화 여부';
COMMENT ON COLUMN bms.tenants.late_fee_waived IS '연체료 면제 여부';
COMMENT ON COLUMN bms.tenants.pets_allowed IS '반려동물 허용 여부';
COMMENT ON COLUMN bms.tenants.pet_details IS '반려동물 상세 (JSON)';
COMMENT ON COLUMN bms.tenants.smoking_allowed IS '흡연 허용 여부';
COMMENT ON COLUMN bms.tenants.parking_spaces IS '주차 공간 수';
COMMENT ON COLUMN bms.tenants.storage_units IS '창고 단위 (JSON)';
COMMENT ON COLUMN bms.tenants.amenities_access IS '편의시설 접근 권한 (JSON)';
COMMENT ON COLUMN bms.tenants.special_terms IS '특별 조건';
COMMENT ON COLUMN bms.tenants.notes IS '비고';
COMMENT ON COLUMN bms.tenants.created_at IS '생성 일시';
COMMENT ON COLUMN bms.tenants.updated_at IS '수정 일시';
COMMENT ON COLUMN bms.tenants.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN bms.tenants.updated_by IS '수정자 사용자 ID';