-- =====================================================
-- 대량 컬럼 커멘트 생성기
-- 모든 테이블의 모든 컬럼에 체계적으로 한글 커멘트 추가
-- =====================================================

-- 작업 지시 테이블 컬럼 커멘트 (실제 존재하는 컬럼들)
COMMENT ON COLUMN bms.work_orders.work_order_number IS '작업 지시 번호';
COMMENT ON COLUMN bms.work_orders.work_type IS '작업 유형';
COMMENT ON COLUMN bms.work_orders.work_category IS '작업 분류';
COMMENT ON COLUMN bms.work_orders.work_title IS '작업 제목';
COMMENT ON COLUMN bms.work_orders.work_description IS '작업 설명';
COMMENT ON COLUMN bms.work_orders.work_priority IS '작업 우선순위';
COMMENT ON COLUMN bms.work_orders.work_urgency IS '작업 긴급도';
COMMENT ON COLUMN bms.work_orders.work_status IS '작업 상태';
COMMENT ON COLUMN bms.work_orders.requested_by IS '요청자 사용자 ID';
COMMENT ON COLUMN bms.work_orders.assigned_to IS '담당자 사용자 ID';
COMMENT ON COLUMN bms.work_orders.assigned_team IS '배정 팀';
COMMENT ON COLUMN bms.work_orders.contractor_id IS '협력업체 식별자 (UUID)';
COMMENT ON COLUMN bms.work_orders.scheduled_start_date IS '예정 시작일';
COMMENT ON COLUMN bms.work_orders.scheduled_end_date IS '예정 종료일';
COMMENT ON COLUMN bms.work_orders.actual_start_date IS '실제 시작일';
COMMENT ON COLUMN bms.work_orders.actual_end_date IS '실제 종료일';
COMMENT ON COLUMN bms.work_orders.estimated_hours IS '예상 작업 시간';
COMMENT ON COLUMN bms.work_orders.actual_hours IS '실제 작업 시간';
COMMENT ON COLUMN bms.work_orders.estimated_cost IS '예상 비용';
COMMENT ON COLUMN bms.work_orders.actual_cost IS '실제 비용';
COMMENT ON COLUMN bms.work_orders.labor_cost IS '인건비';
COMMENT ON COLUMN bms.work_orders.material_cost IS '자재비';
COMMENT ON COLUMN bms.work_orders.equipment_cost IS '장비비';
COMMENT ON COLUMN bms.work_orders.other_costs IS '기타 비용';
COMMENT ON COLUMN bms.work_orders.work_location IS '작업 위치';
COMMENT ON COLUMN bms.work_orders.access_requirements IS '접근 요구사항';
COMMENT ON COLUMN bms.work_orders.safety_requirements IS '안전 요구사항';
COMMENT ON COLUMN bms.work_orders.required_skills IS '필요 기술 (JSON)';
COMMENT ON COLUMN bms.work_orders.required_tools IS '필요 도구 (JSON)';
COMMENT ON COLUMN bms.work_orders.required_materials IS '필요 자재 (JSON)';
COMMENT ON COLUMN bms.work_orders.work_instructions IS '작업 지시사항';
COMMENT ON COLUMN bms.work_orders.quality_standards IS '품질 기준';
COMMENT ON COLUMN bms.work_orders.completion_criteria IS '완료 기준';
COMMENT ON COLUMN bms.work_orders.approval_required IS '승인 필요 여부';
COMMENT ON COLUMN bms.work_orders.approved_by IS '승인자 사용자 ID';
COMMENT ON COLUMN bms.work_orders.approved_at IS '승인 일시';
COMMENT ON COLUMN bms.work_orders.work_notes IS '작업 메모';
COMMENT ON COLUMN bms.work_orders.completion_notes IS '완료 메모';
COMMENT ON COLUMN bms.work_orders.customer_satisfaction IS '고객 만족도';
COMMENT ON COLUMN bms.work_orders.follow_up_required IS '후속 조치 필요 여부';
COMMENT ON COLUMN bms.work_orders.follow_up_date IS '후속 조치일';
COMMENT ON COLUMN bms.work_orders.warranty_period IS '보증 기간 (일)';
COMMENT ON COLUMN bms.work_orders.warranty_start_date IS '보증 시작일';
COMMENT ON COLUMN bms.work_orders.warranty_end_date IS '보증 종료일';

-- 임차인 테이블 컬럼 커멘트 (실제 존재하는 컬럼들)
COMMENT ON COLUMN bms.tenants.tenant_number IS '임차인 번호';
COMMENT ON COLUMN bms.tenants.tenant_type IS '임차인 유형';
COMMENT ON COLUMN bms.tenants.tenant_status IS '임차인 상태';
COMMENT ON COLUMN bms.tenants.primary_tenant_name IS '주 임차인명';
COMMENT ON COLUMN bms.tenants.primary_tenant_phone IS '주 임차인 전화번호';
COMMENT ON COLUMN bms.tenants.primary_tenant_email IS '주 임차인 이메일';
COMMENT ON COLUMN bms.tenants.secondary_tenant_name IS '부 임차인명';
COMMENT ON COLUMN bms.tenants.secondary_tenant_phone IS '부 임차인 전화번호';
COMMENT ON COLUMN bms.tenants.secondary_tenant_email IS '부 임차인 이메일';
COMMENT ON COLUMN bms.tenants.emergency_contact_name IS '비상 연락처명';
COMMENT ON COLUMN bms.tenants.emergency_contact_phone IS '비상 연락처 전화번호';
COMMENT ON COLUMN bms.tenants.emergency_contact_relationship IS '비상 연락처 관계';
COMMENT ON COLUMN bms.tenants.identification_type IS '신분증 유형';
COMMENT ON COLUMN bms.tenants.identification_number IS '신분증 번호';
COMMENT ON COLUMN bms.tenants.date_of_birth IS '생년월일';
COMMENT ON COLUMN bms.tenants.nationality IS '국적';
COMMENT ON COLUMN bms.tenants.occupation IS '직업';
COMMENT ON COLUMN bms.tenants.employer IS '고용주';
COMMENT ON COLUMN bms.tenants.monthly_income IS '월 소득';
COMMENT ON COLUMN bms.tenants.credit_score IS '신용 점수';
COMMENT ON COLUMN bms.tenants.previous_address IS '이전 주소';
COMMENT ON COLUMN bms.tenants.previous_landlord IS '이전 임대인';
COMMENT ON COLUMN bms.tenants.previous_landlord_contact IS '이전 임대인 연락처';
COMMENT ON COLUMN bms.tenants.rental_history IS '임대 이력 (JSON)';
COMMENT ON COLUMN bms.tenants.references IS '추천인 (JSON)';
COMMENT ON COLUMN bms.tenants.background_check_status IS '신원 조회 상태';
COMMENT ON COLUMN bms.tenants.background_check_date IS '신원 조회일';
COMMENT ON COLUMN bms.tenants.move_in_date IS '입주일';
COMMENT ON COLUMN bms.tenants.move_out_date IS '퇴거일';
COMMENT ON COLUMN bms.tenants.lease_start_date IS '임대 시작일';
COMMENT ON COLUMN bms.tenants.lease_end_date IS '임대 종료일';
COMMENT ON COLUMN bms.tenants.lease_renewal_date IS '임대 갱신일';
COMMENT ON COLUMN bms.tenants.rent_amount IS '임대료';
COMMENT ON COLUMN bms.tenants.security_deposit IS '보증금';
COMMENT ON COLUMN bms.tenants.pet_deposit IS '반려동물 보증금';
COMMENT ON COLUMN bms.tenants.key_deposit IS '열쇠 보증금';
COMMENT ON COLUMN bms.tenants.utility_deposit IS '공과금 보증금';
COMMENT ON COLUMN bms.tenants.total_deposits IS '총 보증금';
COMMENT ON COLUMN bms.tenants.payment_method IS '결제 방법';
COMMENT ON COLUMN bms.tenants.bank_account IS '은행 계좌';
COMMENT ON COLUMN bms.tenants.auto_pay_enabled IS '자동 결제 활성화 여부';
COMMENT ON COLUMN bms.tenants.late_fee_waived IS '연체료 면제 여부';
COMMENT ON COLUMN bms.tenants.pets_allowed IS '반려동물 허용 여부';
COMMENT ON COLUMN bms.tenants.pet_details IS '반려동물 상세 (JSON)';
COMMENT ON COLUMN bms.tenants.smoking_allowed IS '흡연 허용 여부';
COMMENT ON COLUMN bms.tenants.parking_spaces IS '주차 공간 수';
COMMENT ON COLUMN bms.tenants.storage_units IS '창고 단위 (JSON)';
COMMENT ON COLUMN bms.tenants.amenities_access IS '편의시설 접근 권한 (JSON)';
COMMENT ON COLUMN bms.tenants.special_terms IS '특별 조건';
COMMENT ON COLUMN bms.tenants.notes IS '비고';

-- 보안 사고 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.security_incidents.incident_number IS '사고 번호';
COMMENT ON COLUMN bms.security_incidents.incident_type IS '사고 유형';
COMMENT ON COLUMN bms.security_incidents.incident_category IS '사고 분류';
COMMENT ON COLUMN bms.security_incidents.severity_level IS '심각도';
COMMENT ON COLUMN bms.security_incidents.incident_title IS '사고 제목';
COMMENT ON COLUMN bms.security_incidents.incident_description IS '사고 설명';
COMMENT ON COLUMN bms.security_incidents.incident_date IS '사고 발생일';
COMMENT ON COLUMN bms.security_incidents.incident_time IS '사고 발생 시간';
COMMENT ON COLUMN bms.security_incidents.reported_date IS '신고일';
COMMENT ON COLUMN bms.security_incidents.reported_by IS '신고자 사용자 ID';
COMMENT ON COLUMN bms.security_incidents.reporter_name IS '신고자명';
COMMENT ON COLUMN bms.security_incidents.reporter_contact IS '신고자 연락처';
COMMENT ON COLUMN bms.security_incidents.incident_location IS '사고 위치';
COMMENT ON COLUMN bms.security_incidents.location_details IS '위치 상세';
COMMENT ON COLUMN bms.security_incidents.environmental_factors IS '환경 요인';
COMMENT ON COLUMN bms.security_incidents.weather_conditions IS '기상 조건';
COMMENT ON COLUMN bms.security_incidents.lighting_conditions IS '조명 조건';
COMMENT ON COLUMN bms.security_incidents.people_involved IS '관련자 (JSON)';
COMMENT ON COLUMN bms.security_incidents.witnesses IS '목격자 (JSON)';
COMMENT ON COLUMN bms.security_incidents.property_damage IS '재산 피해';
COMMENT ON COLUMN bms.security_incidents.damage_cost IS '피해 비용';
COMMENT ON COLUMN bms.security_incidents.equipment_involved IS '관련 장비 (JSON)';
COMMENT ON COLUMN bms.security_incidents.immediate_cause IS '직접 원인';
COMMENT ON COLUMN bms.security_incidents.root_cause IS '근본 원인';
COMMENT ON COLUMN bms.security_incidents.contributing_factors IS '기여 요인 (JSON)';
COMMENT ON COLUMN bms.security_incidents.immediate_actions IS '즉시 조치사항';
COMMENT ON COLUMN bms.security_incidents.corrective_actions IS '시정 조치사항';
COMMENT ON COLUMN bms.security_incidents.preventive_measures IS '예방 조치사항';
COMMENT ON COLUMN bms.security_incidents.investigation_status IS '조사 상태';
COMMENT ON COLUMN bms.security_incidents.investigated_by IS '조사자 사용자 ID';
COMMENT ON COLUMN bms.security_incidents.investigation_date IS '조사일';
COMMENT ON COLUMN bms.security_incidents.investigation_findings IS '조사 결과';
COMMENT ON COLUMN bms.security_incidents.lessons_learned IS '교훈';
COMMENT ON COLUMN bms.security_incidents.training_required IS '교육 필요 여부';
COMMENT ON COLUMN bms.security_incidents.policy_changes IS '정책 변경사항';
COMMENT ON COLUMN bms.security_incidents.regulatory_notification IS '규제 기관 신고 여부';
COMMENT ON COLUMN bms.security_incidents.insurance_claim IS '보험 청구 여부';
COMMENT ON COLUMN bms.security_incidents.claim_number IS '청구 번호';
COMMENT ON COLUMN bms.security_incidents.legal_action IS '법적 조치 여부';

-- 방문자 관리 테이블 컬럼 커멘트
COMMENT ON COLUMN bms.visitor_management.visitor_id IS '방문자 고유 식별자 (UUID)';
COMMENT ON COLUMN bms.visitor_management.visit_number IS '방문 번호';
COMMENT ON COLUMN bms.visitor_management.visitor_name IS '방문자명';
COMMENT ON COLUMN bms.visitor_management.visitor_phone IS '방문자 전화번호';
COMMENT ON COLUMN bms.visitor_management.visitor_email IS '방문자 이메일';
COMMENT ON COLUMN bms.visitor_management.visitor_type IS '방문자 유형';
COMMENT ON COLUMN bms.visitor_management.identification_type IS '신분증 유형';
COMMENT ON COLUMN bms.visitor_management.identification_number IS '신분증 번호';
COMMENT ON COLUMN bms.visitor_management.host_unit_id IS '방문 대상 세대 식별자 (UUID)';
COMMENT ON COLUMN bms.visitor_management.host_name IS '방문 대상자명';
COMMENT ON COLUMN bms.visitor_management.host_phone IS '방문 대상자 전화번호';
COMMENT ON COLUMN bms.visitor_management.visit_purpose IS '방문 목적';
COMMENT ON COLUMN bms.visitor_management.visit_date IS '방문일';
COMMENT ON COLUMN bms.visitor_management.expected_arrival_time IS '예상 도착 시간';
COMMENT ON COLUMN bms.visitor_management.expected_departure_time IS '예상 출발 시간';
COMMENT ON COLUMN bms.visitor_management.actual_arrival_time IS '실제 도착 시간';
COMMENT ON COLUMN bms.visitor_management.actual_departure_time IS '실제 출발 시간';
COMMENT ON COLUMN bms.visitor_management.visit_status IS '방문 상태';
COMMENT ON COLUMN bms.visitor_management.pre_registered IS '사전 등록 여부';
COMMENT ON COLUMN bms.visitor_management.registered_by IS '등록자 사용자 ID';
COMMENT ON COLUMN bms.visitor_management.approved_by IS '승인자 사용자 ID';
COMMENT ON COLUMN bms.visitor_management.approval_status IS '승인 상태';
COMMENT ON COLUMN bms.visitor_management.vehicle_registration IS '차량 번호';
COMMENT ON COLUMN bms.visitor_management.parking_space IS '주차 공간';
COMMENT ON COLUMN bms.visitor_management.access_card_issued IS '출입카드 발급 여부';
COMMENT ON COLUMN bms.visitor_management.access_card_number IS '출입카드 번호';
COMMENT ON COLUMN bms.visitor_management.escort_required IS '에스코트 필요 여부';
COMMENT ON COLUMN bms.visitor_management.escort_assigned IS '에스코트 배정자 사용자 ID';
COMMENT ON COLUMN bms.visitor_management.security_clearance IS '보안 승인';
COMMENT ON COLUMN bms.visitor_management.restricted_areas IS '제한 구역 (JSON)';
COMMENT ON COLUMN bms.visitor_management.special_instructions IS '특별 지시사항';
COMMENT ON COLUMN bms.visitor_management.photo_taken IS '사진 촬영 여부';
COMMENT ON COLUMN bms.visitor_management.photo_path IS '사진 경로';
COMMENT ON COLUMN bms.visitor_management.signature_captured IS '서명 수집 여부';
COMMENT ON COLUMN bms.visitor_management.signature_path IS '서명 경로';
COMMENT ON COLUMN bms.visitor_management.emergency_contact IS '비상 연락처';
COMMENT ON COLUMN bms.visitor_management.health_declaration IS '건강 신고서';
COMMENT ON COLUMN bms.visitor_management.temperature_check IS '체온 측정값';
COMMENT ON COLUMN bms.visitor_management.covid_vaccination_status IS 'COVID 백신 접종 상태';
COMMENT ON COLUMN bms.visitor_management.visit_frequency IS '방문 빈도';
COMMENT ON COLUMN bms.visitor_management.blacklisted IS '블랙리스트 여부';
COMMENT ON COLUMN bms.visitor_management.blacklist_reason IS '블랙리스트 사유';
COMMENT ON COLUMN bms.visitor_management.notes IS '비고';